import React from "react";
import Layout from "../components/Layout";
import { Icon } from "../components/Icon";
import { PageHeader, Card, Button } from "../components/UI";

export default function VisaDetails(){
return <Layout active="Explore Visas"><a href="/dashboard/explore" className="mb-5 inline-flex items-center gap-2 text-sm text-blue-600"><Icon name="back" size={17}/> Back to Explore Visas</a>
<div className="grid gap-5 xl:grid-cols-[1fr_315px]"><div><Card className="overflow-hidden"><div className="relative h-[330px]"><img src="https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1400" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"/><div className="absolute bottom-7 left-7 text-white"><span className="rounded-lg bg-white px-3 py-2 text-sm text-slate-800">🇫🇷 France</span><h1 className="mt-4 text-3xl font-bold">France Schengen Tourist Visa</h1><p className="mt-2 text-sm">⚙ Tourism &nbsp; ◷ Short Stay</p></div><button className="absolute right-5 top-5 text-white"><Icon name="heart"/></button></div>
<div className="grid grid-cols-5 border-b border-slate-100 p-5 text-sm"><div><p className="text-slate-400">Processing time</p><b>15 days</b></div><div><p className="text-slate-400">Validity</p><b>Up to 90 days</b></div><div><p className="text-slate-400">Entry</p><b>Single / Multiple</b></div><div><p className="text-slate-400">Stay</p><b>Up to 90 days</b></div><div><p className="text-slate-400">Price from</p><b>$80</b></div></div>
<div className="flex gap-7 border-b border-slate-100 px-5"><button className="border-b-2 border-blue-600 py-4 text-sm font-semibold text-blue-600">Overview</button>{["Requirements","Fees","Processing","Documents","FAQs"].map(x=><button key={x} className="py-4 text-sm text-slate-500">{x}</button>)}</div>
<div className="p-6"><h3 className="font-semibold">About this Visa</h3><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">The France Schengen Tourist Visa allows you to visit France for tourism, visiting family or friends, or short-term recreation. This visa allows you to travel within the Schengen Area.</p><h3 className="mt-7 font-semibold">Highlights</h3><div className="mt-4 grid gap-4 md:grid-cols-4">{["Explore France","Schengen Access","Tourism & Leisure","Easy Application"].map((x,i)=><div key={x} className="rounded-lg bg-slate-50 p-4"><div className="text-blue-600">◉</div><p className="mt-2 text-sm font-semibold">{x}</p><p className="mt-1 text-xs leading-5 text-slate-500">Simple online process with clear requirements.</p></div>)}</div><h3 className="mt-7 font-semibold">Top Destinations in France</h3><div className="mt-4 grid grid-cols-4 gap-3">{["Paris","Nice","Lyon","Marseille"].map((x,i)=><div key={x}><img src={["https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=500","https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=500","https://images.unsplash.com/photo-1528127269322-539801943592?w=500","https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=500"][i]} className="h-24 w-full rounded-lg object-cover"/><p className="mt-2 text-xs font-semibold">{x}</p></div>)}</div></div></Card></div>
<aside className="space-y-4"><Card className="p-5"><h3 className="font-semibold">Apply for this Visa</h3>{["Simple 3-step application","Secure payment","Track application in real-time","24/7 customer support"].map(x=><p className="mt-4 text-sm" key={x}>✓ {x}</p>)}<a href="/dashboard/applications/new?visaId=france-tourist" className="mt-5 block"><Button>Apply Now</Button></a><Button variant="secondary">♡ Save for Later</Button></Card><Card className="p-5"><h3 className="font-semibold">Need Help?</h3><p className="mt-2 text-sm leading-6 text-slate-500">Our support team is here to help you with your application.</p>{["Live Chat","Email Support","Call Support"].map(x=><div className="mt-3 rounded-lg border p-3 text-sm" key={x}>{x}<span className="float-right">›</span></div>)}</Card><Card className="p-5"><h3 className="font-semibold">Related Visas</h3>{["France Business Visa","France Student Visa","France Family Visit Visa"].map(x=><div className="flex justify-between border-b py-4 text-sm" key={x}><span>{x}</span><span className="text-slate-500">From $90 ›</span></div>)}</Card></aside></div></Layout>
}
