/**
 * Countries Seed Data — complete field set matching the `countries` table.
 *
 * Published countries (isPublished: true) are destinations that have visa
 * types in the visa-types seed. All other countries are seeded as
 * isPublished: false so they exist in the database (for nationality
 * dropdowns etc.) but don't appear as destination pages.
 *
 * visaTypesCount values match the visa-types seed:
 *   AE → 4  TR → 2  IN → 3  KE → 1  EG → 2
 *   LK → 1  KH → 1  ET → 1  AZ → 1  BH → 1
 *   QA → 1  VN → 2
 */

export type CountrySeed = {
  name: string;
  code: string;         // ISO 3166-1 alpha-2
  code3: string;        // ISO 3166-1 alpha-3
  capital?: string;
  region?: string;
  subregion?: string;
  flagEmoji?: string;
  phoneCode?: string;
  currency?: string;
  currencySymbol?: string;
  languages: string[];
  slug: string;
  metaTitle?: string;
  metaDescription?: string;
  heroImageUrl?: string;
  overview?: string;
  travelTips?: string;
  isPublished: boolean;
  visaTypesCount: number;
  avgProcessingDays?: number;
};

// ─────────────────────────────────────────────────────────────
// Helper: builds the default (unpublished) extra fields for a
// country that doesn't yet have visa-type content.
// ─────────────────────────────────────────────────────────────
function base(name: string): Pick<CountrySeed, 'metaTitle' | 'metaDescription' | 'isPublished' | 'visaTypesCount'> {
  return {
    metaTitle: `${name} Visa & Travel Information | VisaFlow`,
    metaDescription: `Visa requirements, entry rules, and travel information for ${name}. Apply online with VisaFlow.`,
    isPublished: false,
    visaTypesCount: 0,
  };
}

export const countriesData: CountrySeed[] = [

  // ═══════════════════════════════════════════════════════════
  // PUBLISHED DESTINATIONS (have visa types in the seed)
  // ═══════════════════════════════════════════════════════════

  {
    name: 'United Arab Emirates',
    code: 'AE', code3: 'ARE',
    capital: 'Abu Dhabi',
    region: 'Asia', subregion: 'Western Asia',
    flagEmoji: '🇦🇪', phoneCode: '+971',
    currency: 'AED', currencySymbol: 'د.إ',
    languages: ['Arabic', 'English'],
    slug: 'united-arab-emirates',
    metaTitle: 'UAE Visa Online — Apply for Dubai & Abu Dhabi Tourist Visa | VisaFlow',
    metaDescription: 'Apply for UAE tourist, transit, or long-stay visa online. Fast processing, e-Visa for 30 or 60 days. Get your Dubai visa in 3–7 business days.',
    overview: 'The United Arab Emirates is a federation of seven emirates on the Arabian Peninsula, best known for the ultramodern skylines of Dubai and Abu Dhabi, world-class shopping, and record-breaking attractions. Visitors enjoy year-round sunshine, pristine beaches along the Arabian Gulf, and seamless connectivity as a global travel hub. Dubai alone draws over 16 million tourists a year with its mix of luxury, adventure tourism, and cultural heritage in areas like Al Fahidi Historic District.',
    travelTips: 'Dress modestly in public areas and religious sites. Alcohol is served only in licensed venues such as hotels and restaurants. The UAE follows a Saturday–Sunday weekend. Ramadan significantly changes opening hours and public dining rules — plan accordingly. Tap water is safe to drink. Public transport in Dubai (Metro, Tram, Bus) is excellent and uses the Nol card system. Tipping 10–15% at restaurants is appreciated but not obligatory.',
    isPublished: true,
    visaTypesCount: 4,
    avgProcessingDays: 5,
  },

  {
    name: 'Turkey',
    code: 'TR', code3: 'TUR',
    capital: 'Ankara',
    region: 'Asia', subregion: 'Western Asia',
    flagEmoji: '🇹🇷', phoneCode: '+90',
    currency: 'TRY', currencySymbol: '₺',
    languages: ['Turkish'],
    slug: 'turkey',
    metaTitle: 'Turkey e-Visa — Apply Online for Turkish Tourist Visa | VisaFlow',
    metaDescription: 'Get your Turkey e-Visa in as little as 24 hours. Single or multiple-entry options available. Official e-Visa for tourism and business visits.',
    overview: 'Turkey is a transcontinental country straddling Europe and Asia, offering an extraordinary blend of history, culture, and natural beauty. From the iconic Blue Mosque and Hagia Sophia in Istanbul to the fairy-chimneys of Cappadocia and the turquoise coasts of the Aegean and Mediterranean, Turkey delivers unforgettable experiences. The country boasts some of the world\'s finest cuisine, warm hospitality, and more UNESCO World Heritage Sites than almost any other nation.',
    travelTips: 'The Turkish Lira fluctuates significantly — exchange currency at local exchange offices (döviz) for better rates than airports. Istanbul\'s public transport runs on the Istanbulkart card, reusable and efficient. Haggling is expected and respected in bazaars. Carry cash for smaller restaurants and local markets. Tap water is generally not recommended for drinking in major cities — bottled water is cheap and widely available. Always remove shoes when entering mosques.',
    isPublished: true,
    visaTypesCount: 2,
    avgProcessingDays: 2,
  },

  {
    name: 'India',
    code: 'IN', code3: 'IND',
    capital: 'New Delhi',
    region: 'Asia', subregion: 'South Asia',
    flagEmoji: '🇮🇳', phoneCode: '+91',
    currency: 'INR', currencySymbol: '₹',
    languages: ['Hindi', 'English'],
    slug: 'india',
    metaTitle: 'India e-Visa Online — Tourist, Business & Medical Visa | VisaFlow',
    metaDescription: 'Apply for India e-Tourist or e-Business Visa online. 30-day, 1-year, and 5-year options. Fast government e-Visa processing in 2–4 business days.',
    overview: 'India is the world\'s largest democracy and a land of staggering diversity — 1.4 billion people, 22 official languages, and civilisations that span 5,000 years. Travellers discover ancient temples, Himalayan trekking, vibrant megacities, pristine backwaters in Kerala, and wildlife safaris in national parks. The Golden Triangle (Delhi, Agra, Jaipur) is one of the world\'s most popular tourist circuits, while Goa, Rajasthan, and Varanasi each offer entirely different but equally compelling experiences.',
    travelTips: 'Book trains in advance on IRCTC — popular routes sell out weeks ahead. Negotiate auto-rickshaw fares before getting in, or use Ola/Uber for metered rides. Drink only bottled or filtered water. Street food is an essential experience but choose busy stalls with high turnover. Respect dress codes at religious sites — carry a scarf or shawl. E-Visa holders must enter through designated international airports; check the list before booking. Tipping is customary — round up taxi fares and tip hotel staff ₹50–₹100.',
    isPublished: true,
    visaTypesCount: 3,
    avgProcessingDays: 3,
  },

  {
    name: 'Kenya',
    code: 'KE', code3: 'KEN',
    capital: 'Nairobi',
    region: 'Africa', subregion: 'Sub-Saharan Africa',
    flagEmoji: '🇰🇪', phoneCode: '+254',
    currency: 'KES', currencySymbol: 'Sh',
    languages: ['English', 'Swahili'],
    slug: 'kenya',
    metaTitle: 'Kenya e-Visa (ETA) — Apply Online for Kenya Tourist Visa | VisaFlow',
    metaDescription: 'Apply for Kenya Electronic Travel Authorization (ETA) online. Valid 90 days single entry. Fast processing for tourism and business visits to Kenya.',
    overview: 'Kenya is East Africa\'s most iconic safari destination, home to the Maasai Mara National Reserve where the Great Migration — one of nature\'s greatest spectacles — unfolds each year. Beyond wildlife, Kenya offers dramatic landscapes ranging from Mount Kenya\'s snow-capped peaks to the white-sand beaches of Diani and Watamu on the Indian Ocean coast. Nairobi is a vibrant modern capital with a thriving food and arts scene, and the country is a hub for adventure sports including hot air ballooning, hiking, and diving.',
    travelTips: 'Yellow fever vaccination is mandatory if arriving from certain countries — carry your International Certificate of Vaccination. Anti-malarial medication is recommended, especially outside Nairobi and the coast. M-Pesa mobile money is ubiquitous; many local vendors only accept it. Safari parks have strict rules — stay in your vehicle and follow guide instructions at all times. Book reputable licensed guides and camps in advance during peak season (July–October). Altitude sickness is a risk above 3,500m on Mount Kenya.',
    isPublished: true,
    visaTypesCount: 1,
    avgProcessingDays: 5,
  },

  {
    name: 'Egypt',
    code: 'EG', code3: 'EGY',
    capital: 'Cairo',
    region: 'Africa', subregion: 'Northern Africa',
    flagEmoji: '🇪🇬', phoneCode: '+20',
    currency: 'EGP', currencySymbol: '£',
    languages: ['Arabic'],
    slug: 'egypt',
    metaTitle: 'Egypt e-Visa Online — Apply for Egyptian Tourist Visa | VisaFlow',
    metaDescription: 'Apply for Egypt e-Visa online. Single or multiple entry options, 30-day stay. Fast processing in 3–7 days. Visit the Pyramids, Luxor, and the Red Sea.',
    overview: 'Egypt is home to one of humanity\'s oldest and most extraordinary civilisations. The Great Pyramids of Giza and the Sphinx stand on the outskirts of Cairo, while Luxor contains the world\'s greatest concentration of ancient monuments including Karnak Temple and the Valley of the Kings. The Nile River cruise between Luxor and Aswan is a classic journey, and the Red Sea resorts of Hurghada and Sharm el-Sheikh offer world-class diving and snorkelling. Egypt\'s ancient history, Islamic heritage, and Coptic Christian sites create a remarkable tapestry for travellers.',
    travelTips: 'Negotiate prices firmly in bazaars — the first quoted price is rarely the final one. Drink only bottled water. Tipping (baksheesh) is expected for many services, including at monuments — carry small change. Dress conservatively outside beach resorts, especially at religious sites. Photography at some monuments requires a fee or is restricted. Ramadan significantly changes local rhythms. Avoid tap water and ice from unknown sources. Register with your embassy if staying more than a week.',
    isPublished: true,
    visaTypesCount: 2,
    avgProcessingDays: 5,
  },

  {
    name: 'Sri Lanka',
    code: 'LK', code3: 'LKA',
    capital: 'Colombo',
    region: 'Asia', subregion: 'South Asia',
    flagEmoji: '🇱🇰', phoneCode: '+94',
    currency: 'LKR', currencySymbol: 'Rs',
    languages: ['Sinhala', 'Tamil'],
    slug: 'sri-lanka',
    metaTitle: 'Sri Lanka ETA — Apply for Sri Lanka Tourist Visa Online | VisaFlow',
    metaDescription: 'Get your Sri Lanka Electronic Travel Authorization (ETA) online. 30-day multiple entry, processed in 1–3 days. Explore temples, beaches, and wildlife.',
    overview: 'Sri Lanka is a teardrop-shaped island off the southern tip of India, packing extraordinary diversity into a small area. Ancient Buddhist temples at Sigiriya and Anuradhapura, emerald tea plantations in the Hill Country around Nuwara Eliya, blue whale watching off Mirissa, elephant safaris in Yala National Park, and pristine beaches on the south and east coasts make Sri Lanka one of Asia\'s most rewarding destinations. The cuisine — rich curries, hoppers, and fresh seafood — is outstanding and affordable.',
    travelTips: 'The train journey from Colombo through the tea country to Ella is one of the world\'s great scenic rail rides — book in advance. Tuk-tuks are the primary short-distance transport; agree the fare before departing. Dress modestly and remove shoes and hats at Buddhist and Hindu temples. Elephants in the wild should be observed from a distance; avoid venues that offer elephant rides. Dengue fever is present — use mosquito repellent. The northeast monsoon (October–January) affects the east coast while the southwest monsoon affects the west and south.',
    isPublished: true,
    visaTypesCount: 1,
    avgProcessingDays: 2,
  },

  {
    name: 'Cambodia',
    code: 'KH', code3: 'KHM',
    capital: 'Phnom Penh',
    region: 'Asia', subregion: 'Southeast Asia',
    flagEmoji: '🇰🇭', phoneCode: '+855',
    currency: 'KHR', currencySymbol: '៛',
    languages: ['Khmer'],
    slug: 'cambodia',
    metaTitle: 'Cambodia e-Visa Online — Apply for Cambodian Tourist Visa | VisaFlow',
    metaDescription: 'Apply for Cambodia e-Visa online. Single entry, 30-day stay, valid 90 days from issue. Visit Angkor Wat and the temples of Siem Reap quickly and easily.',
    overview: 'Cambodia is home to one of the world\'s greatest archaeological wonders — the temple complex of Angkor, a UNESCO World Heritage Site and the largest religious monument on Earth. Beyond Angkor, Cambodia offers the French-colonial charm of Phnom Penh, the jungle-smothered ruins of Koh Ker, pristine beaches on the islands of Koh Rong and Koh Rong Sanloem, and the rich, tragic history of the Khmer Rouge era preserved at Tuol Sleng and the Killing Fields. The country is warm, welcoming, and one of Southeast Asia\'s most affordable destinations.',
    travelTips: 'US dollars are widely accepted alongside Cambodian Riel — ATMs and payments often deal in dollars. Sun protection is essential; temperatures regularly exceed 35°C. Bargaining is normal in markets. Visit Angkor at sunrise or late afternoon to avoid both heat and crowds. Be respectful at temples — cover shoulders and knees. Cambodia does not have the best road infrastructure outside cities; allow extra travel time for intercity journeys. Avoid plastic bag and straw use; Cambodia is working hard to reduce plastic pollution.',
    isPublished: true,
    visaTypesCount: 1,
    avgProcessingDays: 4,
  },

  {
    name: 'Ethiopia',
    code: 'ET', code3: 'ETH',
    capital: 'Addis Ababa',
    region: 'Africa', subregion: 'Sub-Saharan Africa',
    flagEmoji: '🇪🇹', phoneCode: '+251',
    currency: 'ETB', currencySymbol: 'Br',
    languages: ['Amharic'],
    slug: 'ethiopia',
    metaTitle: 'Ethiopia e-Visa Online — Apply for Ethiopian Tourist Visa | VisaFlow',
    metaDescription: 'Apply for Ethiopia e-Visa online. Single entry, 30-day stay. Explore Lalibela, the Simien Mountains, and Addis Ababa. Processed in 3–5 business days.',
    overview: 'Ethiopia is one of Africa\'s most historically and culturally rich countries, and the only African nation never colonised. It is home to rock-hewn churches at Lalibela that date to the 12th century, the ancient stelae of Axum, the Simien Mountains trekking routes, and the unique Danakil Depression — one of the hottest and most otherworldly places on Earth. Addis Ababa, at 2,355m, is Africa\'s political capital and hosts the African Union headquarters. Ethiopia is the birthplace of coffee, and the traditional coffee ceremony is central to social life.',
    travelTips: 'E-Visa is only valid for entry via Addis Ababa Bole International Airport — land border entries require a different visa. Yellow fever vaccination is required from endemic-country travellers. Altitude sickness can affect visitors to Addis Ababa and highland areas. Drink only bottled water. Birr cannot be imported or exported — exchange currency at official bureaux. The Ethiopian calendar has 13 months and runs approximately 7–8 years behind the Gregorian calendar — confirm dates carefully when planning. Photography of military installations, airports, and some government buildings is prohibited.',
    isPublished: true,
    visaTypesCount: 1,
    avgProcessingDays: 4,
  },

  {
    name: 'Azerbaijan',
    code: 'AZ', code3: 'AZE',
    capital: 'Baku',
    region: 'Asia', subregion: 'Western Asia',
    flagEmoji: '🇦🇿', phoneCode: '+994',
    currency: 'AZN', currencySymbol: '₼',
    languages: ['Azerbaijani'],
    slug: 'azerbaijan',
    metaTitle: 'Azerbaijan ASAN e-Visa Online — Apply for Azerbaijani Visa | VisaFlow',
    metaDescription: 'Apply for Azerbaijan ASAN e-Visa online. Single entry, 30-day stay, processed in just 3 business days. Visit Baku\'s Old City and the Caucasus Mountains.',
    overview: 'Azerbaijan is a fascinating crossroads country on the Caspian Sea where Europe meets Asia in the South Caucasus. The capital Baku blends futuristic architecture — including the iconic Flame Towers — with a UNESCO-listed medieval Old City (Icherisheher) of narrow lanes and ancient caravanserais. Beyond Baku, the country offers the mud volcanoes of Gobustan, the alpine villages of the Caucasus Mountains in Sheki and Quba, and the rich silk-road heritage of Ganja. Azerbaijan is a fast-rising tourism destination known for hospitality, distinctive cuisine, and some of the world\'s most efficient e-Visa processing.',
    travelTips: 'The ASAN e-Visa system is one of the world\'s fastest — processing is typically exactly 3 business days. Baku\'s Old City requires comfortable footwear — the cobblestones are uneven. Azerbaijan is secular but dress modestly at mosques and in rural areas. Azerbaijani cuisine centres around rice, lamb, and herbs; dolma and plov are national dishes. Credit cards are widely accepted in Baku but carry Manat cash outside the capital. The currency cannot be exported — exchange remaining Manat at the airport before departure. Photography near government buildings and military sites is restricted.',
    isPublished: true,
    visaTypesCount: 1,
    avgProcessingDays: 3,
  },

  {
    name: 'Bahrain',
    code: 'BH', code3: 'BHR',
    capital: 'Manama',
    region: 'Asia', subregion: 'Western Asia',
    flagEmoji: '🇧🇭', phoneCode: '+973',
    currency: 'BHD', currencySymbol: '.د.ب',
    languages: ['Arabic'],
    slug: 'bahrain',
    metaTitle: 'Bahrain e-Visa Online — Apply for Bahraini Tourist Visa | VisaFlow',
    metaDescription: 'Apply for Bahrain e-Visa online. Single entry 14-day stay, processed in 1–3 days. Explore Manama\'s markets, the F1 circuit, and Bahrain\'s pearl heritage.',
    overview: 'Bahrain is a small but dynamic island kingdom in the Arabian Gulf, punching well above its weight as a regional financial and cultural hub. The capital Manama is a cosmopolitan city with gleaming towers, vibrant souks, and an increasingly acclaimed food scene. The UNESCO-listed Qal\'at al-Bahrain (Bahrain Fort), the Bahrain National Museum, and the ancient burial mounds of Dilmun speak to a 4,000-year civilisation. Bahrain hosts the Formula 1 Gulf Air Grand Prix at the Sakhir Circuit and is known for being more socially liberal than many of its Gulf neighbours.',
    travelTips: 'Bahrain is accessible by the King Fahd Causeway from Saudi Arabia by road. Public transport is limited — taxis and Uber are the most practical options. Summer temperatures (June–September) can reach 45°C; most activities are indoor during midday. The Bahrain Dinar is one of the world\'s highest-valued currencies — check exchange rates carefully. Alcohol is served in licensed hotels and restaurants. Friday is a holy day; many businesses open Saturday–Wednesday. Dress modestly in traditional areas and markets.',
    isPublished: true,
    visaTypesCount: 1,
    avgProcessingDays: 2,
  },

  {
    name: 'Qatar',
    code: 'QA', code3: 'QAT',
    capital: 'Doha',
    region: 'Asia', subregion: 'Western Asia',
    flagEmoji: '🇶🇦', phoneCode: '+974',
    currency: 'QAR', currencySymbol: 'ر.ق',
    languages: ['Arabic'],
    slug: 'qatar',
    metaTitle: 'Qatar Tourist Visa Online — Apply for Qatar Hayya Visa | VisaFlow',
    metaDescription: 'Apply for Qatar tourist visa online. 30-day single entry, processed in 2–5 days. Explore Doha\'s souks, museums, and desert experiences.',
    overview: 'Qatar is a high-income peninsular state on the Arabian Gulf that has transformed itself into a global arts, sports, and tourism destination in less than a generation. Doha\'s striking skyline along the Corniche is punctuated by world-class museums including the I.M. Pei-designed Museum of Islamic Art. The Souq Waqif is a beautifully restored traditional market. The country hosted the FIFA World Cup 2022, cementing its global profile. Desert safaris into the dramatic sand dunes of the inland sea at Khor Al Adaid, kayaking through the mangroves of Al Thakira, and dining at some of the Middle East\'s finest restaurants make Qatar a compelling destination.',
    travelTips: 'Hamad International Airport regularly ranks among the world\'s best — it\'s a pleasure to transit through. Dress modestly in public, especially at souqs, mosques, and government buildings. Alcohol is only available at licensed hotel bars and restaurants — public consumption is illegal. During Ramadan, eating and drinking in public during daylight hours is not permitted. Qatar is extremely safe with very low crime rates. The Doha Metro covers the main tourist areas efficiently. Summer heat (May–September) is extreme; most events and attractions are indoors during this period.',
    isPublished: true,
    visaTypesCount: 1,
    avgProcessingDays: 3,
  },

  {
    name: 'Vietnam',
    code: 'VN', code3: 'VNM',
    capital: 'Hanoi',
    region: 'Asia', subregion: 'Southeast Asia',
    flagEmoji: '🇻🇳', phoneCode: '+84',
    currency: 'VND', currencySymbol: '₫',
    languages: ['Vietnamese'],
    slug: 'vietnam',
    metaTitle: 'Vietnam e-Visa Online — Apply for Vietnamese Tourist Visa | VisaFlow',
    metaDescription: 'Apply for Vietnam e-Visa online. 90-day single or multiple entry, processed in 3–5 days. Explore Ha Long Bay, Hoi An, and Ho Chi Minh City.',
    overview: 'Vietnam is a long, S-shaped country stretching over 3,000km along the eastern coast of the Indochina Peninsula, offering an astonishing variety of landscapes and experiences. Ha Long Bay\'s karst limestone islands are one of Asia\'s most iconic sights; the ancient trading town of Hoi An glows with lanterns at night; Hanoi\'s Old Quarter buzzes with a thousand years of history; and Ho Chi Minh City pulses with modern energy. Vietnam\'s cuisine — including pho, banh mi, and fresh spring rolls — is celebrated worldwide, and the country\'s affordability makes it one of Southeast Asia\'s best-value destinations.',
    travelTips: 'Vietnamese Dong is only available inside Vietnam — exchange currency on arrival. Traffic in Hanoi and Ho Chi Minh City is intense; cross roads slowly and steadily. Book the Reunification Express train between cities well in advance — sleeper cabins are very popular. The climate varies dramatically between north and south, and the central coast has its own distinct monsoon season — research the weather by region and time of year before planning your itinerary. Bargaining is normal in markets but not in restaurants with menus. Always carry a photo ID copy; your passport may be held by some accommodation.',
    isPublished: true,
    visaTypesCount: 2,
    avgProcessingDays: 4,
  },

  // ═══════════════════════════════════════════════════════════
  // ALL OTHER COUNTRIES (isPublished: false, visaTypesCount: 0)
  // ═══════════════════════════════════════════════════════════

  // ─── Africa ───────────────────────────────────────────────
  { name: 'Algeria', code: 'DZ', code3: 'DZA', capital: 'Algiers', region: 'Africa', subregion: 'Northern Africa', flagEmoji: '🇩🇿', phoneCode: '+213', currency: 'DZD', currencySymbol: 'د.ج', languages: ['Arabic', 'French'], slug: 'algeria', ...base('Algeria') },
  { name: 'Angola', code: 'AO', code3: 'AGO', capital: 'Luanda', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇦🇴', phoneCode: '+244', currency: 'AOA', currencySymbol: 'Kz', languages: ['Portuguese'], slug: 'angola', ...base('Angola') },
  { name: 'Benin', code: 'BJ', code3: 'BEN', capital: 'Porto-Novo', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇧🇯', phoneCode: '+229', currency: 'XOF', currencySymbol: 'Fr', languages: ['French'], slug: 'benin', ...base('Benin') },
  { name: 'Botswana', code: 'BW', code3: 'BWA', capital: 'Gaborone', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇧🇼', phoneCode: '+267', currency: 'BWP', currencySymbol: 'P', languages: ['English', 'Setswana'], slug: 'botswana', ...base('Botswana') },
  { name: 'Burkina Faso', code: 'BF', code3: 'BFA', capital: 'Ouagadougou', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇧🇫', phoneCode: '+226', currency: 'XOF', currencySymbol: 'Fr', languages: ['French'], slug: 'burkina-faso', ...base('Burkina Faso') },
  { name: 'Burundi', code: 'BI', code3: 'BDI', capital: 'Gitega', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇧🇮', phoneCode: '+257', currency: 'BIF', currencySymbol: 'Fr', languages: ['Kirundi', 'French'], slug: 'burundi', ...base('Burundi') },
  { name: 'Cameroon', code: 'CM', code3: 'CMR', capital: 'Yaoundé', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇨🇲', phoneCode: '+237', currency: 'XAF', currencySymbol: 'Fr', languages: ['French', 'English'], slug: 'cameroon', ...base('Cameroon') },
  { name: 'Cape Verde', code: 'CV', code3: 'CPV', capital: 'Praia', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇨🇻', phoneCode: '+238', currency: 'CVE', currencySymbol: '$', languages: ['Portuguese'], slug: 'cape-verde', ...base('Cape Verde') },
  { name: 'Central African Republic', code: 'CF', code3: 'CAF', capital: 'Bangui', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇨🇫', phoneCode: '+236', currency: 'XAF', currencySymbol: 'Fr', languages: ['French', 'Sango'], slug: 'central-african-republic', ...base('Central African Republic') },
  { name: 'Chad', code: 'TD', code3: 'TCD', capital: "N'Djamena", region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇹🇩', phoneCode: '+235', currency: 'XAF', currencySymbol: 'Fr', languages: ['French', 'Arabic'], slug: 'chad', ...base('Chad') },
  { name: 'Comoros', code: 'KM', code3: 'COM', capital: 'Moroni', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇰🇲', phoneCode: '+269', currency: 'KMF', currencySymbol: 'Fr', languages: ['French', 'Comorian'], slug: 'comoros', ...base('Comoros') },
  { name: 'Congo', code: 'CG', code3: 'COG', capital: 'Brazzaville', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇨🇬', phoneCode: '+242', currency: 'XAF', currencySymbol: 'Fr', languages: ['French'], slug: 'congo', ...base('Congo') },
  { name: 'Democratic Republic of the Congo', code: 'CD', code3: 'COD', capital: 'Kinshasa', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇨🇩', phoneCode: '+243', currency: 'CDF', currencySymbol: 'Fr', languages: ['French', 'Lingala'], slug: 'democratic-republic-congo', ...base('Democratic Republic of the Congo') },
  { name: "Côte d'Ivoire", code: 'CI', code3: 'CIV', capital: 'Yamoussoukro', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇨🇮', phoneCode: '+225', currency: 'XOF', currencySymbol: 'Fr', languages: ['French'], slug: 'cote-divoire', ...base("Côte d'Ivoire") },
  { name: 'Djibouti', code: 'DJ', code3: 'DJI', capital: 'Djibouti', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇩🇯', phoneCode: '+253', currency: 'DJF', currencySymbol: 'Fr', languages: ['French', 'Arabic'], slug: 'djibouti', ...base('Djibouti') },
  { name: 'Equatorial Guinea', code: 'GQ', code3: 'GNQ', capital: 'Malabo', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇬🇶', phoneCode: '+240', currency: 'XAF', currencySymbol: 'Fr', languages: ['Spanish', 'French', 'Portuguese'], slug: 'equatorial-guinea', ...base('Equatorial Guinea') },
  { name: 'Eritrea', code: 'ER', code3: 'ERI', capital: 'Asmara', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇪🇷', phoneCode: '+291', currency: 'ERN', currencySymbol: 'Nfk', languages: ['Tigrinya', 'Arabic'], slug: 'eritrea', ...base('Eritrea') },
  { name: 'Eswatini', code: 'SZ', code3: 'SWZ', capital: 'Mbabane', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇸🇿', phoneCode: '+268', currency: 'SZL', currencySymbol: 'L', languages: ['English', 'Swati'], slug: 'eswatini', ...base('Eswatini') },
  { name: 'Gabon', code: 'GA', code3: 'GAB', capital: 'Libreville', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇬🇦', phoneCode: '+241', currency: 'XAF', currencySymbol: 'Fr', languages: ['French'], slug: 'gabon', ...base('Gabon') },
  { name: 'Gambia', code: 'GM', code3: 'GMB', capital: 'Banjul', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇬🇲', phoneCode: '+220', currency: 'GMD', currencySymbol: 'D', languages: ['English'], slug: 'gambia', ...base('Gambia') },
  { name: 'Ghana', code: 'GH', code3: 'GHA', capital: 'Accra', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇬🇭', phoneCode: '+233', currency: 'GHS', currencySymbol: '₵', languages: ['English'], slug: 'ghana', ...base('Ghana') },
  { name: 'Guinea', code: 'GN', code3: 'GIN', capital: 'Conakry', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇬🇳', phoneCode: '+224', currency: 'GNF', currencySymbol: 'Fr', languages: ['French'], slug: 'guinea', ...base('Guinea') },
  { name: 'Guinea-Bissau', code: 'GW', code3: 'GNB', capital: 'Bissau', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇬🇼', phoneCode: '+245', currency: 'XOF', currencySymbol: 'Fr', languages: ['Portuguese'], slug: 'guinea-bissau', ...base('Guinea-Bissau') },
  { name: 'Lesotho', code: 'LS', code3: 'LSO', capital: 'Maseru', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇱🇸', phoneCode: '+266', currency: 'LSL', currencySymbol: 'L', languages: ['English', 'Sotho'], slug: 'lesotho', ...base('Lesotho') },
  { name: 'Liberia', code: 'LR', code3: 'LBR', capital: 'Monrovia', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇱🇷', phoneCode: '+231', currency: 'LRD', currencySymbol: '$', languages: ['English'], slug: 'liberia', ...base('Liberia') },
  { name: 'Libya', code: 'LY', code3: 'LBY', capital: 'Tripoli', region: 'Africa', subregion: 'Northern Africa', flagEmoji: '🇱🇾', phoneCode: '+218', currency: 'LYD', currencySymbol: 'LD', languages: ['Arabic'], slug: 'libya', ...base('Libya') },
  { name: 'Madagascar', code: 'MG', code3: 'MDG', capital: 'Antananarivo', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇲🇬', phoneCode: '+261', currency: 'MGA', currencySymbol: 'Ar', languages: ['Malagasy', 'French'], slug: 'madagascar', ...base('Madagascar') },
  { name: 'Malawi', code: 'MW', code3: 'MWI', capital: 'Lilongwe', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇲🇼', phoneCode: '+265', currency: 'MWK', currencySymbol: 'MK', languages: ['English', 'Chichewa'], slug: 'malawi', ...base('Malawi') },
  { name: 'Mali', code: 'ML', code3: 'MLI', capital: 'Bamako', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇲🇱', phoneCode: '+223', currency: 'XOF', currencySymbol: 'Fr', languages: ['French'], slug: 'mali', ...base('Mali') },
  { name: 'Mauritania', code: 'MR', code3: 'MRT', capital: 'Nouakchott', region: 'Africa', subregion: 'Northern Africa', flagEmoji: '🇲🇷', phoneCode: '+222', currency: 'MRU', currencySymbol: 'UM', languages: ['Arabic', 'French'], slug: 'mauritania', ...base('Mauritania') },
  { name: 'Mauritius', code: 'MU', code3: 'MUS', capital: 'Port Louis', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇲🇺', phoneCode: '+230', currency: 'MUR', currencySymbol: '₨', languages: ['English', 'French'], slug: 'mauritius', ...base('Mauritius') },
  { name: 'Morocco', code: 'MA', code3: 'MAR', capital: 'Rabat', region: 'Africa', subregion: 'Northern Africa', flagEmoji: '🇲🇦', phoneCode: '+212', currency: 'MAD', currencySymbol: 'د.م.', languages: ['Arabic', 'French', 'Berber'], slug: 'morocco', ...base('Morocco') },
  { name: 'Mozambique', code: 'MZ', code3: 'MOZ', capital: 'Maputo', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇲🇿', phoneCode: '+258', currency: 'MZN', currencySymbol: 'MT', languages: ['Portuguese'], slug: 'mozambique', ...base('Mozambique') },
  { name: 'Namibia', code: 'NA', code3: 'NAM', capital: 'Windhoek', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇳🇦', phoneCode: '+264', currency: 'NAD', currencySymbol: '$', languages: ['English', 'Afrikaans'], slug: 'namibia', ...base('Namibia') },
  { name: 'Niger', code: 'NE', code3: 'NER', capital: 'Niamey', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇳🇪', phoneCode: '+227', currency: 'XOF', currencySymbol: 'Fr', languages: ['French'], slug: 'niger', ...base('Niger') },
  { name: 'Nigeria', code: 'NG', code3: 'NGA', capital: 'Abuja', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇳🇬', phoneCode: '+234', currency: 'NGN', currencySymbol: '₦', languages: ['English'], slug: 'nigeria', ...base('Nigeria') },
  { name: 'Rwanda', code: 'RW', code3: 'RWA', capital: 'Kigali', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇷🇼', phoneCode: '+250', currency: 'RWF', currencySymbol: 'Fr', languages: ['Kinyarwanda', 'English', 'French'], slug: 'rwanda', ...base('Rwanda') },
  { name: 'Sao Tome and Principe', code: 'ST', code3: 'STP', capital: 'São Tomé', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇸🇹', phoneCode: '+239', currency: 'STN', currencySymbol: 'Db', languages: ['Portuguese'], slug: 'sao-tome-principe', ...base('Sao Tome and Principe') },
  { name: 'Senegal', code: 'SN', code3: 'SEN', capital: 'Dakar', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇸🇳', phoneCode: '+221', currency: 'XOF', currencySymbol: 'Fr', languages: ['French', 'Wolof'], slug: 'senegal', ...base('Senegal') },
  { name: 'Seychelles', code: 'SC', code3: 'SYC', capital: 'Victoria', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇸🇨', phoneCode: '+248', currency: 'SCR', currencySymbol: '₨', languages: ['English', 'French', 'Seychellois Creole'], slug: 'seychelles', ...base('Seychelles') },
  { name: 'Sierra Leone', code: 'SL', code3: 'SLE', capital: 'Freetown', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇸🇱', phoneCode: '+232', currency: 'SLL', currencySymbol: 'Le', languages: ['English'], slug: 'sierra-leone', ...base('Sierra Leone') },
  { name: 'Somalia', code: 'SO', code3: 'SOM', capital: 'Mogadishu', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇸🇴', phoneCode: '+252', currency: 'SOS', currencySymbol: 'Sh', languages: ['Somali', 'Arabic'], slug: 'somalia', ...base('Somalia') },
  { name: 'South Africa', code: 'ZA', code3: 'ZAF', capital: 'Pretoria', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇿🇦', phoneCode: '+27', currency: 'ZAR', currencySymbol: 'R', languages: ['English', 'Zulu', 'Afrikaans'], slug: 'south-africa', ...base('South Africa') },
  { name: 'South Sudan', code: 'SS', code3: 'SSD', capital: 'Juba', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇸🇸', phoneCode: '+211', currency: 'SSP', currencySymbol: '£', languages: ['English'], slug: 'south-sudan', ...base('South Sudan') },
  { name: 'Sudan', code: 'SD', code3: 'SDN', capital: 'Khartoum', region: 'Africa', subregion: 'Northern Africa', flagEmoji: '🇸🇩', phoneCode: '+249', currency: 'SDG', currencySymbol: '£', languages: ['Arabic', 'English'], slug: 'sudan', ...base('Sudan') },
  { name: 'Togo', code: 'TG', code3: 'TGO', capital: 'Lomé', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇹🇬', phoneCode: '+228', currency: 'XOF', currencySymbol: 'Fr', languages: ['French'], slug: 'togo', ...base('Togo') },
  { name: 'Tunisia', code: 'TN', code3: 'TUN', capital: 'Tunis', region: 'Africa', subregion: 'Northern Africa', flagEmoji: '🇹🇳', phoneCode: '+216', currency: 'TND', currencySymbol: 'د.ت', languages: ['Arabic', 'French'], slug: 'tunisia', ...base('Tunisia') },
  { name: 'Uganda', code: 'UG', code3: 'UGA', capital: 'Kampala', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇺🇬', phoneCode: '+256', currency: 'UGX', currencySymbol: 'Sh', languages: ['English', 'Swahili'], slug: 'uganda', ...base('Uganda') },
  { name: 'Zambia', code: 'ZM', code3: 'ZMB', capital: 'Lusaka', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇿🇲', phoneCode: '+260', currency: 'ZMW', currencySymbol: 'ZK', languages: ['English'], slug: 'zambia', ...base('Zambia') },
  { name: 'Zimbabwe', code: 'ZW', code3: 'ZWE', capital: 'Harare', region: 'Africa', subregion: 'Sub-Saharan Africa', flagEmoji: '🇿🇼', phoneCode: '+263', currency: 'ZWL', currencySymbol: '$', languages: ['English', 'Shona'], slug: 'zimbabwe', ...base('Zimbabwe') },

  // ─── Asia ──────────────────────────────────────────────────
  { name: 'Afghanistan', code: 'AF', code3: 'AFG', capital: 'Kabul', region: 'Asia', subregion: 'South Asia', flagEmoji: '🇦🇫', phoneCode: '+93', currency: 'AFN', currencySymbol: '؋', languages: ['Dari', 'Pashto'], slug: 'afghanistan', ...base('Afghanistan') },
  { name: 'Bangladesh', code: 'BD', code3: 'BGD', capital: 'Dhaka', region: 'Asia', subregion: 'South Asia', flagEmoji: '🇧🇩', phoneCode: '+880', currency: 'BDT', currencySymbol: '৳', languages: ['Bengali'], slug: 'bangladesh', ...base('Bangladesh') },
  { name: 'Bhutan', code: 'BT', code3: 'BTN', capital: 'Thimphu', region: 'Asia', subregion: 'South Asia', flagEmoji: '🇧🇹', phoneCode: '+975', currency: 'BTN', currencySymbol: 'Nu.', languages: ['Dzongkha'], slug: 'bhutan', ...base('Bhutan') },
  { name: 'Brunei', code: 'BN', code3: 'BRN', capital: 'Bandar Seri Begawan', region: 'Asia', subregion: 'Southeast Asia', flagEmoji: '🇧🇳', phoneCode: '+673', currency: 'BND', currencySymbol: '$', languages: ['Malay', 'English'], slug: 'brunei', ...base('Brunei') },
  { name: 'China', code: 'CN', code3: 'CHN', capital: 'Beijing', region: 'Asia', subregion: 'East Asia', flagEmoji: '🇨🇳', phoneCode: '+86', currency: 'CNY', currencySymbol: '¥', languages: ['Mandarin Chinese'], slug: 'china', ...base('China') },
  { name: 'East Timor', code: 'TL', code3: 'TLS', capital: 'Dili', region: 'Asia', subregion: 'Southeast Asia', flagEmoji: '🇹🇱', phoneCode: '+670', currency: 'USD', currencySymbol: '$', languages: ['Tetum', 'Portuguese'], slug: 'east-timor', ...base('East Timor') },
  { name: 'Hong Kong', code: 'HK', code3: 'HKG', capital: 'Victoria', region: 'Asia', subregion: 'East Asia', flagEmoji: '🇭🇰', phoneCode: '+852', currency: 'HKD', currencySymbol: '$', languages: ['Cantonese', 'English'], slug: 'hong-kong', ...base('Hong Kong') },
  { name: 'Indonesia', code: 'ID', code3: 'IDN', capital: 'Jakarta', region: 'Asia', subregion: 'Southeast Asia', flagEmoji: '🇮🇩', phoneCode: '+62', currency: 'IDR', currencySymbol: 'Rp', languages: ['Indonesian'], slug: 'indonesia', ...base('Indonesia') },
  { name: 'Iran', code: 'IR', code3: 'IRN', capital: 'Tehran', region: 'Asia', subregion: 'Western Asia', flagEmoji: '🇮🇷', phoneCode: '+98', currency: 'IRR', currencySymbol: '﷼', languages: ['Persian'], slug: 'iran', ...base('Iran') },
  { name: 'Iraq', code: 'IQ', code3: 'IRQ', capital: 'Baghdad', region: 'Asia', subregion: 'Western Asia', flagEmoji: '🇮🇶', phoneCode: '+964', currency: 'IQD', currencySymbol: 'ع.د', languages: ['Arabic', 'Kurdish'], slug: 'iraq', ...base('Iraq') },
  { name: 'Israel', code: 'IL', code3: 'ISR', capital: 'Jerusalem', region: 'Asia', subregion: 'Western Asia', flagEmoji: '🇮🇱', phoneCode: '+972', currency: 'ILS', currencySymbol: '₪', languages: ['Hebrew', 'Arabic'], slug: 'israel', ...base('Israel') },
  { name: 'Japan', code: 'JP', code3: 'JPN', capital: 'Tokyo', region: 'Asia', subregion: 'East Asia', flagEmoji: '🇯🇵', phoneCode: '+81', currency: 'JPY', currencySymbol: '¥', languages: ['Japanese'], slug: 'japan', ...base('Japan') },
  { name: 'Jordan', code: 'JO', code3: 'JOR', capital: 'Amman', region: 'Asia', subregion: 'Western Asia', flagEmoji: '🇯🇴', phoneCode: '+962', currency: 'JOD', currencySymbol: 'د.ا', languages: ['Arabic'], slug: 'jordan', ...base('Jordan') },
  { name: 'Kazakhstan', code: 'KZ', code3: 'KAZ', capital: 'Astana', region: 'Asia', subregion: 'Central Asia', flagEmoji: '🇰🇿', phoneCode: '+7', currency: 'KZT', currencySymbol: '₸', languages: ['Kazakh', 'Russian'], slug: 'kazakhstan', ...base('Kazakhstan') },
  { name: 'Kuwait', code: 'KW', code3: 'KWT', capital: 'Kuwait City', region: 'Asia', subregion: 'Western Asia', flagEmoji: '🇰🇼', phoneCode: '+965', currency: 'KWD', currencySymbol: 'د.ك', languages: ['Arabic'], slug: 'kuwait', ...base('Kuwait') },
  { name: 'Kyrgyzstan', code: 'KG', code3: 'KGZ', capital: 'Bishkek', region: 'Asia', subregion: 'Central Asia', flagEmoji: '🇰🇬', phoneCode: '+996', currency: 'KGS', currencySymbol: 'с', languages: ['Kyrgyz', 'Russian'], slug: 'kyrgyzstan', ...base('Kyrgyzstan') },
  { name: 'Laos', code: 'LA', code3: 'LAO', capital: 'Vientiane', region: 'Asia', subregion: 'Southeast Asia', flagEmoji: '🇱🇦', phoneCode: '+856', currency: 'LAK', currencySymbol: '₭', languages: ['Lao'], slug: 'laos', ...base('Laos') },
  { name: 'Lebanon', code: 'LB', code3: 'LBN', capital: 'Beirut', region: 'Asia', subregion: 'Western Asia', flagEmoji: '🇱🇧', phoneCode: '+961', currency: 'LBP', currencySymbol: 'ل.ل', languages: ['Arabic', 'French', 'English'], slug: 'lebanon', ...base('Lebanon') },
  { name: 'Macao', code: 'MO', code3: 'MAC', capital: 'Macau', region: 'Asia', subregion: 'East Asia', flagEmoji: '🇲🇴', phoneCode: '+853', currency: 'MOP', currencySymbol: 'P', languages: ['Cantonese', 'Mandarin Chinese'], slug: 'macao', ...base('Macao') },
  { name: 'Malaysia', code: 'MY', code3: 'MYS', capital: 'Kuala Lumpur', region: 'Asia', subregion: 'Southeast Asia', flagEmoji: '🇲🇾', phoneCode: '+60', currency: 'MYR', currencySymbol: 'RM', languages: ['Malay', 'English'], slug: 'malaysia', ...base('Malaysia') },
  { name: 'Maldives', code: 'MV', code3: 'MDV', capital: 'Malé', region: 'Asia', subregion: 'South Asia', flagEmoji: '🇲🇻', phoneCode: '+960', currency: 'MVR', currencySymbol: 'Rf', languages: ['Dhivehi'], slug: 'maldives', ...base('Maldives') },
  { name: 'Mongolia', code: 'MN', code3: 'MNG', capital: 'Ulaanbaatar', region: 'Asia', subregion: 'East Asia', flagEmoji: '🇲🇳', phoneCode: '+976', currency: 'MNT', currencySymbol: '₮', languages: ['Mongolian'], slug: 'mongolia', ...base('Mongolia') },
  { name: 'Myanmar', code: 'MM', code3: 'MMR', capital: 'Naypyidaw', region: 'Asia', subregion: 'Southeast Asia', flagEmoji: '🇲🇲', phoneCode: '+95', currency: 'MMK', currencySymbol: 'K', languages: ['Burmese'], slug: 'myanmar', ...base('Myanmar') },
  { name: 'Nepal', code: 'NP', code3: 'NPL', capital: 'Kathmandu', region: 'Asia', subregion: 'South Asia', flagEmoji: '🇳🇵', phoneCode: '+977', currency: 'NPR', currencySymbol: '₨', languages: ['Nepali'], slug: 'nepal', ...base('Nepal') },
  { name: 'North Korea', code: 'KP', code3: 'PRK', capital: 'Pyongyang', region: 'Asia', subregion: 'East Asia', flagEmoji: '🇰🇵', phoneCode: '+850', currency: 'KPW', currencySymbol: '₩', languages: ['Korean'], slug: 'north-korea', ...base('North Korea') },
  { name: 'Oman', code: 'OM', code3: 'OMN', capital: 'Muscat', region: 'Asia', subregion: 'Western Asia', flagEmoji: '🇴🇲', phoneCode: '+968', currency: 'OMR', currencySymbol: 'ر.ع.', languages: ['Arabic'], slug: 'oman', ...base('Oman') },
  { name: 'Pakistan', code: 'PK', code3: 'PAK', capital: 'Islamabad', region: 'Asia', subregion: 'South Asia', flagEmoji: '🇵🇰', phoneCode: '+92', currency: 'PKR', currencySymbol: '₨', languages: ['Urdu', 'English'], slug: 'pakistan', ...base('Pakistan') },
  { name: 'Palestine', code: 'PS', code3: 'PSE', capital: 'Ramallah', region: 'Asia', subregion: 'Western Asia', flagEmoji: '🇵🇸', phoneCode: '+970', currency: 'ILS', currencySymbol: '₪', languages: ['Arabic'], slug: 'palestine', ...base('Palestine') },
  { name: 'Philippines', code: 'PH', code3: 'PHL', capital: 'Manila', region: 'Asia', subregion: 'Southeast Asia', flagEmoji: '🇵🇭', phoneCode: '+63', currency: 'PHP', currencySymbol: '₱', languages: ['Filipino', 'English'], slug: 'philippines', ...base('Philippines') },
  { name: 'Saudi Arabia', code: 'SA', code3: 'SAU', capital: 'Riyadh', region: 'Asia', subregion: 'Western Asia', flagEmoji: '🇸🇦', phoneCode: '+966', currency: 'SAR', currencySymbol: 'ر.س', languages: ['Arabic'], slug: 'saudi-arabia', ...base('Saudi Arabia') },
  { name: 'Singapore', code: 'SG', code3: 'SGP', capital: 'Singapore', region: 'Asia', subregion: 'Southeast Asia', flagEmoji: '🇸🇬', phoneCode: '+65', currency: 'SGD', currencySymbol: '$', languages: ['English', 'Mandarin', 'Malay', 'Tamil'], slug: 'singapore', ...base('Singapore') },
  { name: 'South Korea', code: 'KR', code3: 'KOR', capital: 'Seoul', region: 'Asia', subregion: 'East Asia', flagEmoji: '🇰🇷', phoneCode: '+82', currency: 'KRW', currencySymbol: '₩', languages: ['Korean'], slug: 'south-korea', ...base('South Korea') },
  { name: 'Syria', code: 'SY', code3: 'SYR', capital: 'Damascus', region: 'Asia', subregion: 'Western Asia', flagEmoji: '🇸🇾', phoneCode: '+963', currency: 'SYP', currencySymbol: '£', languages: ['Arabic'], slug: 'syria', ...base('Syria') },
  { name: 'Taiwan', code: 'TW', code3: 'TWN', capital: 'Taipei', region: 'Asia', subregion: 'East Asia', flagEmoji: '🇹🇼', phoneCode: '+886', currency: 'TWD', currencySymbol: '$', languages: ['Mandarin Chinese'], slug: 'taiwan', ...base('Taiwan') },
  { name: 'Tajikistan', code: 'TJ', code3: 'TJK', capital: 'Dushanbe', region: 'Asia', subregion: 'Central Asia', flagEmoji: '🇹🇯', phoneCode: '+992', currency: 'TJS', currencySymbol: 'ЅМ', languages: ['Tajik', 'Russian'], slug: 'tajikistan', ...base('Tajikistan') },
  { name: 'Thailand', code: 'TH', code3: 'THA', capital: 'Bangkok', region: 'Asia', subregion: 'Southeast Asia', flagEmoji: '🇹🇭', phoneCode: '+66', currency: 'THB', currencySymbol: '฿', languages: ['Thai'], slug: 'thailand', ...base('Thailand') },
  { name: 'Turkmenistan', code: 'TM', code3: 'TKM', capital: 'Ashgabat', region: 'Asia', subregion: 'Central Asia', flagEmoji: '🇹🇲', phoneCode: '+993', currency: 'TMT', currencySymbol: 'm', languages: ['Turkmen', 'Russian'], slug: 'turkmenistan', ...base('Turkmenistan') },
  { name: 'Uzbekistan', code: 'UZ', code3: 'UZB', capital: 'Tashkent', region: 'Asia', subregion: 'Central Asia', flagEmoji: '🇺🇿', phoneCode: '+998', currency: 'UZS', currencySymbol: "so'm", languages: ['Uzbek', 'Russian'], slug: 'uzbekistan', ...base('Uzbekistan') },
  { name: 'Yemen', code: 'YE', code3: 'YEM', capital: "Sana'a", region: 'Asia', subregion: 'Western Asia', flagEmoji: '🇾🇪', phoneCode: '+967', currency: 'YER', currencySymbol: '﷼', languages: ['Arabic'], slug: 'yemen', ...base('Yemen') },

  // ─── Europe ────────────────────────────────────────────────
  { name: 'Albania', code: 'AL', code3: 'ALB', capital: 'Tirana', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇦🇱', phoneCode: '+355', currency: 'ALL', currencySymbol: 'L', languages: ['Albanian'], slug: 'albania', ...base('Albania') },
  { name: 'Andorra', code: 'AD', code3: 'AND', capital: 'Andorra la Vella', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇦🇩', phoneCode: '+376', currency: 'EUR', currencySymbol: '€', languages: ['Catalan'], slug: 'andorra', ...base('Andorra') },
  { name: 'Austria', code: 'AT', code3: 'AUT', capital: 'Vienna', region: 'Europe', subregion: 'Central Europe', flagEmoji: '🇦🇹', phoneCode: '+43', currency: 'EUR', currencySymbol: '€', languages: ['German'], slug: 'austria', ...base('Austria') },
  { name: 'Belarus', code: 'BY', code3: 'BLR', capital: 'Minsk', region: 'Europe', subregion: 'Eastern Europe', flagEmoji: '🇧🇾', phoneCode: '+375', currency: 'BYN', currencySymbol: 'Br', languages: ['Belarusian', 'Russian'], slug: 'belarus', ...base('Belarus') },
  { name: 'Belgium', code: 'BE', code3: 'BEL', capital: 'Brussels', region: 'Europe', subregion: 'Northern Europe', flagEmoji: '🇧🇪', phoneCode: '+32', currency: 'EUR', currencySymbol: '€', languages: ['Dutch', 'French', 'German'], slug: 'belgium', ...base('Belgium') },
  { name: 'Bosnia and Herzegovina', code: 'BA', code3: 'BIH', capital: 'Sarajevo', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇧🇦', phoneCode: '+387', currency: 'BAM', currencySymbol: 'KM', languages: ['Bosnian', 'Serbian', 'Croatian'], slug: 'bosnia-herzegovina', ...base('Bosnia and Herzegovina') },
  { name: 'Bulgaria', code: 'BG', code3: 'BGR', capital: 'Sofia', region: 'Europe', subregion: 'Eastern Europe', flagEmoji: '🇧🇬', phoneCode: '+359', currency: 'BGN', currencySymbol: 'лв', languages: ['Bulgarian'], slug: 'bulgaria', ...base('Bulgaria') },
  { name: 'Croatia', code: 'HR', code3: 'HRV', capital: 'Zagreb', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇭🇷', phoneCode: '+385', currency: 'EUR', currencySymbol: '€', languages: ['Croatian'], slug: 'croatia', ...base('Croatia') },
  { name: 'Cyprus', code: 'CY', code3: 'CYP', capital: 'Nicosia', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇨🇾', phoneCode: '+357', currency: 'EUR', currencySymbol: '€', languages: ['Greek', 'Turkish'], slug: 'cyprus', ...base('Cyprus') },
  { name: 'Czechia', code: 'CZ', code3: 'CZE', capital: 'Prague', region: 'Europe', subregion: 'Central Europe', flagEmoji: '🇨🇿', phoneCode: '+420', currency: 'CZK', currencySymbol: 'Kč', languages: ['Czech'], slug: 'czechia', ...base('Czechia') },
  { name: 'Denmark', code: 'DK', code3: 'DNK', capital: 'Copenhagen', region: 'Europe', subregion: 'Northern Europe', flagEmoji: '🇩🇰', phoneCode: '+45', currency: 'DKK', currencySymbol: 'kr', languages: ['Danish'], slug: 'denmark', ...base('Denmark') },
  { name: 'Estonia', code: 'EE', code3: 'EST', capital: 'Tallinn', region: 'Europe', subregion: 'Northern Europe', flagEmoji: '🇪🇪', phoneCode: '+372', currency: 'EUR', currencySymbol: '€', languages: ['Estonian'], slug: 'estonia', ...base('Estonia') },
  { name: 'Finland', code: 'FI', code3: 'FIN', capital: 'Helsinki', region: 'Europe', subregion: 'Northern Europe', flagEmoji: '🇫🇮', phoneCode: '+358', currency: 'EUR', currencySymbol: '€', languages: ['Finnish', 'Swedish'], slug: 'finland', ...base('Finland') },
  { name: 'France', code: 'FR', code3: 'FRA', capital: 'Paris', region: 'Europe', subregion: 'Western Europe', flagEmoji: '🇫🇷', phoneCode: '+33', currency: 'EUR', currencySymbol: '€', languages: ['French'], slug: 'france', ...base('France') },
  { name: 'Germany', code: 'DE', code3: 'DEU', capital: 'Berlin', region: 'Europe', subregion: 'Central Europe', flagEmoji: '🇩🇪', phoneCode: '+49', currency: 'EUR', currencySymbol: '€', languages: ['German'], slug: 'germany', ...base('Germany') },
  { name: 'Greece', code: 'GR', code3: 'GRC', capital: 'Athens', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇬🇷', phoneCode: '+30', currency: 'EUR', currencySymbol: '€', languages: ['Greek'], slug: 'greece', ...base('Greece') },
  { name: 'Hungary', code: 'HU', code3: 'HUN', capital: 'Budapest', region: 'Europe', subregion: 'Central Europe', flagEmoji: '🇭🇺', phoneCode: '+36', currency: 'HUF', currencySymbol: 'Ft', languages: ['Hungarian'], slug: 'hungary', ...base('Hungary') },
  { name: 'Iceland', code: 'IS', code3: 'ISL', capital: 'Reykjavik', region: 'Europe', subregion: 'Northern Europe', flagEmoji: '🇮🇸', phoneCode: '+354', currency: 'ISK', currencySymbol: 'kr', languages: ['Icelandic'], slug: 'iceland', ...base('Iceland') },
  { name: 'Ireland', code: 'IE', code3: 'IRL', capital: 'Dublin', region: 'Europe', subregion: 'Northern Europe', flagEmoji: '🇮🇪', phoneCode: '+353', currency: 'EUR', currencySymbol: '€', languages: ['English', 'Irish'], slug: 'ireland', ...base('Ireland') },
  { name: 'Italy', code: 'IT', code3: 'ITA', capital: 'Rome', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇮🇹', phoneCode: '+39', currency: 'EUR', currencySymbol: '€', languages: ['Italian'], slug: 'italy', ...base('Italy') },
  { name: 'Kosovo', code: 'XK', code3: 'XKX', capital: 'Pristina', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇽🇰', phoneCode: '+383', currency: 'EUR', currencySymbol: '€', languages: ['Albanian', 'Serbian'], slug: 'kosovo', ...base('Kosovo') },
  { name: 'Latvia', code: 'LV', code3: 'LVA', capital: 'Riga', region: 'Europe', subregion: 'Northern Europe', flagEmoji: '🇱🇻', phoneCode: '+371', currency: 'EUR', currencySymbol: '€', languages: ['Latvian'], slug: 'latvia', ...base('Latvia') },
  { name: 'Liechtenstein', code: 'LI', code3: 'LIE', capital: 'Vaduz', region: 'Europe', subregion: 'Central Europe', flagEmoji: '🇱🇮', phoneCode: '+423', currency: 'CHF', currencySymbol: 'Fr', languages: ['German'], slug: 'liechtenstein', ...base('Liechtenstein') },
  { name: 'Lithuania', code: 'LT', code3: 'LTU', capital: 'Vilnius', region: 'Europe', subregion: 'Northern Europe', flagEmoji: '🇱🇹', phoneCode: '+370', currency: 'EUR', currencySymbol: '€', languages: ['Lithuanian'], slug: 'lithuania', ...base('Lithuania') },
  { name: 'Luxembourg', code: 'LU', code3: 'LUX', capital: 'Luxembourg City', region: 'Europe', subregion: 'Western Europe', flagEmoji: '🇱🇺', phoneCode: '+352', currency: 'EUR', currencySymbol: '€', languages: ['Luxembourgish', 'French', 'German'], slug: 'luxembourg', ...base('Luxembourg') },
  { name: 'Malta', code: 'MT', code3: 'MLT', capital: 'Valletta', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇲🇹', phoneCode: '+356', currency: 'EUR', currencySymbol: '€', languages: ['Maltese', 'English'], slug: 'malta', ...base('Malta') },
  { name: 'Moldova', code: 'MD', code3: 'MDA', capital: 'Chișinău', region: 'Europe', subregion: 'Eastern Europe', flagEmoji: '🇲🇩', phoneCode: '+373', currency: 'MDL', currencySymbol: 'L', languages: ['Romanian'], slug: 'moldova', ...base('Moldova') },
  { name: 'Monaco', code: 'MC', code3: 'MCO', capital: 'Monaco', region: 'Europe', subregion: 'Western Europe', flagEmoji: '🇲🇨', phoneCode: '+377', currency: 'EUR', currencySymbol: '€', languages: ['French'], slug: 'monaco', ...base('Monaco') },
  { name: 'Montenegro', code: 'ME', code3: 'MNE', capital: 'Podgorica', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇲🇪', phoneCode: '+382', currency: 'EUR', currencySymbol: '€', languages: ['Montenegrin'], slug: 'montenegro', ...base('Montenegro') },
  { name: 'Netherlands', code: 'NL', code3: 'NLD', capital: 'Amsterdam', region: 'Europe', subregion: 'Western Europe', flagEmoji: '🇳🇱', phoneCode: '+31', currency: 'EUR', currencySymbol: '€', languages: ['Dutch'], slug: 'netherlands', ...base('Netherlands') },
  { name: 'North Macedonia', code: 'MK', code3: 'MKD', capital: 'Skopje', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇲🇰', phoneCode: '+389', currency: 'MKD', currencySymbol: 'ден', languages: ['Macedonian'], slug: 'north-macedonia', ...base('North Macedonia') },
  { name: 'Norway', code: 'NO', code3: 'NOR', capital: 'Oslo', region: 'Europe', subregion: 'Northern Europe', flagEmoji: '🇳🇴', phoneCode: '+47', currency: 'NOK', currencySymbol: 'kr', languages: ['Norwegian'], slug: 'norway', ...base('Norway') },
  { name: 'Poland', code: 'PL', code3: 'POL', capital: 'Warsaw', region: 'Europe', subregion: 'Central Europe', flagEmoji: '🇵🇱', phoneCode: '+48', currency: 'PLN', currencySymbol: 'zł', languages: ['Polish'], slug: 'poland', ...base('Poland') },
  { name: 'Portugal', code: 'PT', code3: 'PRT', capital: 'Lisbon', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇵🇹', phoneCode: '+351', currency: 'EUR', currencySymbol: '€', languages: ['Portuguese'], slug: 'portugal', ...base('Portugal') },
  { name: 'Romania', code: 'RO', code3: 'ROU', capital: 'Bucharest', region: 'Europe', subregion: 'Central Europe', flagEmoji: '🇷🇴', phoneCode: '+40', currency: 'RON', currencySymbol: 'lei', languages: ['Romanian'], slug: 'romania', ...base('Romania') },
  { name: 'Russia', code: 'RU', code3: 'RUS', capital: 'Moscow', region: 'Europe', subregion: 'Eastern Europe', flagEmoji: '🇷🇺', phoneCode: '+7', currency: 'RUB', currencySymbol: '₽', languages: ['Russian'], slug: 'russia', ...base('Russia') },
  { name: 'San Marino', code: 'SM', code3: 'SMR', capital: 'San Marino', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇸🇲', phoneCode: '+378', currency: 'EUR', currencySymbol: '€', languages: ['Italian'], slug: 'san-marino', ...base('San Marino') },
  { name: 'Serbia', code: 'RS', code3: 'SRB', capital: 'Belgrade', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇷🇸', phoneCode: '+381', currency: 'RSD', currencySymbol: 'дин', languages: ['Serbian'], slug: 'serbia', ...base('Serbia') },
  { name: 'Slovakia', code: 'SK', code3: 'SVK', capital: 'Bratislava', region: 'Europe', subregion: 'Central Europe', flagEmoji: '🇸🇰', phoneCode: '+421', currency: 'EUR', currencySymbol: '€', languages: ['Slovak'], slug: 'slovakia', ...base('Slovakia') },
  { name: 'Slovenia', code: 'SI', code3: 'SVN', capital: 'Ljubljana', region: 'Europe', subregion: 'Central Europe', flagEmoji: '🇸🇮', phoneCode: '+386', currency: 'EUR', currencySymbol: '€', languages: ['Slovenian'], slug: 'slovenia', ...base('Slovenia') },
  { name: 'Spain', code: 'ES', code3: 'ESP', capital: 'Madrid', region: 'Europe', subregion: 'Southern Europe', flagEmoji: '🇪🇸', phoneCode: '+34', currency: 'EUR', currencySymbol: '€', languages: ['Spanish'], slug: 'spain', ...base('Spain') },
  { name: 'Sweden', code: 'SE', code3: 'SWE', capital: 'Stockholm', region: 'Europe', subregion: 'Northern Europe', flagEmoji: '🇸🇪', phoneCode: '+46', currency: 'SEK', currencySymbol: 'kr', languages: ['Swedish'], slug: 'sweden', ...base('Sweden') },
  { name: 'Switzerland', code: 'CH', code3: 'CHE', capital: 'Bern', region: 'Europe', subregion: 'Central Europe', flagEmoji: '🇨🇭', phoneCode: '+41', currency: 'CHF', currencySymbol: 'Fr', languages: ['German', 'French', 'Italian', 'Romansh'], slug: 'switzerland', ...base('Switzerland') },
  { name: 'Ukraine', code: 'UA', code3: 'UKR', capital: 'Kyiv', region: 'Europe', subregion: 'Eastern Europe', flagEmoji: '🇺🇦', phoneCode: '+380', currency: 'UAH', currencySymbol: '₴', languages: ['Ukrainian', 'Russian'], slug: 'ukraine', ...base('Ukraine') },
  { name: 'United Kingdom', code: 'GB', code3: 'GBR', capital: 'London', region: 'Europe', subregion: 'Northern Europe', flagEmoji: '🇬🇧', phoneCode: '+44', currency: 'GBP', currencySymbol: '£', languages: ['English'], slug: 'united-kingdom', ...base('United Kingdom') },

  // ─── North America ─────────────────────────────────────────
  { name: 'Antigua and Barbuda', code: 'AG', code3: 'ATG', capital: "Saint John's", region: 'North America', subregion: 'Caribbean', flagEmoji: '🇦🇬', phoneCode: '+1', currency: 'XCD', currencySymbol: '$', languages: ['English'], slug: 'antigua-barbuda', ...base('Antigua and Barbuda') },
  { name: 'Bahamas', code: 'BS', code3: 'BHS', capital: 'Nassau', region: 'North America', subregion: 'Caribbean', flagEmoji: '🇧🇸', phoneCode: '+1', currency: 'BSD', currencySymbol: '$', languages: ['English'], slug: 'bahamas', ...base('Bahamas') },
  { name: 'Barbados', code: 'BB', code3: 'BRB', capital: 'Bridgetown', region: 'North America', subregion: 'Caribbean', flagEmoji: '🇧🇧', phoneCode: '+1', currency: 'BBD', currencySymbol: '$', languages: ['English'], slug: 'barbados', ...base('Barbados') },
  { name: 'Belize', code: 'BZ', code3: 'BLZ', capital: 'Belmopan', region: 'North America', subregion: 'Central America', flagEmoji: '🇧🇿', phoneCode: '+501', currency: 'BZD', currencySymbol: '$', languages: ['English'], slug: 'belize', ...base('Belize') },
  { name: 'Canada', code: 'CA', code3: 'CAN', capital: 'Ottawa', region: 'North America', subregion: 'Northern America', flagEmoji: '🇨🇦', phoneCode: '+1', currency: 'CAD', currencySymbol: '$', languages: ['English', 'French'], slug: 'canada', ...base('Canada') },
  { name: 'Costa Rica', code: 'CR', code3: 'CRI', capital: 'San José', region: 'North America', subregion: 'Central America', flagEmoji: '🇨🇷', phoneCode: '+506', currency: 'CRC', currencySymbol: '₡', languages: ['Spanish'], slug: 'costa-rica', ...base('Costa Rica') },
  { name: 'Cuba', code: 'CU', code3: 'CUB', capital: 'Havana', region: 'North America', subregion: 'Caribbean', flagEmoji: '🇨🇺', phoneCode: '+53', currency: 'CUP', currencySymbol: '₱', languages: ['Spanish'], slug: 'cuba', ...base('Cuba') },
  { name: 'Dominica', code: 'DM', code3: 'DMA', capital: 'Roseau', region: 'North America', subregion: 'Caribbean', flagEmoji: '🇩🇲', phoneCode: '+1', currency: 'XCD', currencySymbol: '$', languages: ['English'], slug: 'dominica', ...base('Dominica') },
  { name: 'Dominican Republic', code: 'DO', code3: 'DOM', capital: 'Santo Domingo', region: 'North America', subregion: 'Caribbean', flagEmoji: '🇩🇴', phoneCode: '+1', currency: 'DOP', currencySymbol: '$', languages: ['Spanish'], slug: 'dominican-republic', ...base('Dominican Republic') },
  { name: 'El Salvador', code: 'SV', code3: 'SLV', capital: 'San Salvador', region: 'North America', subregion: 'Central America', flagEmoji: '🇸🇻', phoneCode: '+503', currency: 'SVC', currencySymbol: '$', languages: ['Spanish'], slug: 'el-salvador', ...base('El Salvador') },
  { name: 'Grenada', code: 'GD', code3: 'GRD', capital: "Saint George's", region: 'North America', subregion: 'Caribbean', flagEmoji: '🇬🇩', phoneCode: '+1', currency: 'XCD', currencySymbol: '$', languages: ['English'], slug: 'grenada', ...base('Grenada') },
  { name: 'Guatemala', code: 'GT', code3: 'GTM', capital: 'Guatemala City', region: 'North America', subregion: 'Central America', flagEmoji: '🇬🇹', phoneCode: '+502', currency: 'GTQ', currencySymbol: 'Q', languages: ['Spanish'], slug: 'guatemala', ...base('Guatemala') },
  { name: 'Haiti', code: 'HT', code3: 'HTI', capital: 'Port-au-Prince', region: 'North America', subregion: 'Caribbean', flagEmoji: '🇭🇹', phoneCode: '+509', currency: 'HTG', currencySymbol: 'G', languages: ['French', 'Haitian Creole'], slug: 'haiti', ...base('Haiti') },
  { name: 'Honduras', code: 'HN', code3: 'HND', capital: 'Tegucigalpa', region: 'North America', subregion: 'Central America', flagEmoji: '🇭🇳', phoneCode: '+504', currency: 'HNL', currencySymbol: 'L', languages: ['Spanish'], slug: 'honduras', ...base('Honduras') },
  { name: 'Jamaica', code: 'JM', code3: 'JAM', capital: 'Kingston', region: 'North America', subregion: 'Caribbean', flagEmoji: '🇯🇲', phoneCode: '+1', currency: 'JMD', currencySymbol: '$', languages: ['English'], slug: 'jamaica', ...base('Jamaica') },
  { name: 'Mexico', code: 'MX', code3: 'MEX', capital: 'Mexico City', region: 'North America', subregion: 'Central America', flagEmoji: '🇲🇽', phoneCode: '+52', currency: 'MXN', currencySymbol: '$', languages: ['Spanish'], slug: 'mexico', ...base('Mexico') },
  { name: 'Nicaragua', code: 'NI', code3: 'NIC', capital: 'Managua', region: 'North America', subregion: 'Central America', flagEmoji: '🇳🇮', phoneCode: '+505', currency: 'NIO', currencySymbol: 'C$', languages: ['Spanish'], slug: 'nicaragua', ...base('Nicaragua') },
  { name: 'Panama', code: 'PA', code3: 'PAN', capital: 'Panama City', region: 'North America', subregion: 'Central America', flagEmoji: '🇵🇦', phoneCode: '+507', currency: 'PAB', currencySymbol: 'B/.', languages: ['Spanish', 'English'], slug: 'panama', ...base('Panama') },
  { name: 'Saint Kitts and Nevis', code: 'KN', code3: 'KNA', capital: 'Basseterre', region: 'North America', subregion: 'Caribbean', flagEmoji: '🇰🇳', phoneCode: '+1', currency: 'XCD', currencySymbol: '$', languages: ['English'], slug: 'saint-kitts-nevis', ...base('Saint Kitts and Nevis') },
  { name: 'Saint Lucia', code: 'LC', code3: 'LCA', capital: 'Castries', region: 'North America', subregion: 'Caribbean', flagEmoji: '🇱🇨', phoneCode: '+1', currency: 'XCD', currencySymbol: '$', languages: ['English'], slug: 'saint-lucia', ...base('Saint Lucia') },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', code3: 'VCT', capital: 'Kingstown', region: 'North America', subregion: 'Caribbean', flagEmoji: '🇻🇨', phoneCode: '+1', currency: 'XCD', currencySymbol: '$', languages: ['English'], slug: 'saint-vincent-grenadines', ...base('Saint Vincent and the Grenadines') },
  { name: 'Trinidad and Tobago', code: 'TT', code3: 'TTO', capital: 'Port of Spain', region: 'North America', subregion: 'Caribbean', flagEmoji: '🇹🇹', phoneCode: '+1', currency: 'TTD', currencySymbol: '$', languages: ['English'], slug: 'trinidad-tobago', ...base('Trinidad and Tobago') },
  { name: 'United States', code: 'US', code3: 'USA', capital: 'Washington D.C.', region: 'North America', subregion: 'Northern America', flagEmoji: '🇺🇸', phoneCode: '+1', currency: 'USD', currencySymbol: '$', languages: ['English'], slug: 'united-states', ...base('United States') },

  // ─── South America ─────────────────────────────────────────
  { name: 'Argentina', code: 'AR', code3: 'ARG', capital: 'Buenos Aires', region: 'South America', subregion: 'South America', flagEmoji: '🇦🇷', phoneCode: '+54', currency: 'ARS', currencySymbol: '$', languages: ['Spanish'], slug: 'argentina', ...base('Argentina') },
  { name: 'Bolivia', code: 'BO', code3: 'BOL', capital: 'La Paz', region: 'South America', subregion: 'South America', flagEmoji: '🇧🇴', phoneCode: '+591', currency: 'BOB', currencySymbol: 'Bs', languages: ['Spanish', 'Quechua', 'Aymara'], slug: 'bolivia', ...base('Bolivia') },
  { name: 'Brazil', code: 'BR', code3: 'BRA', capital: 'Brasília', region: 'South America', subregion: 'South America', flagEmoji: '🇧🇷', phoneCode: '+55', currency: 'BRL', currencySymbol: 'R$', languages: ['Portuguese'], slug: 'brazil', ...base('Brazil') },
  { name: 'Chile', code: 'CL', code3: 'CHL', capital: 'Santiago', region: 'South America', subregion: 'South America', flagEmoji: '🇨🇱', phoneCode: '+56', currency: 'CLP', currencySymbol: '$', languages: ['Spanish'], slug: 'chile', ...base('Chile') },
  { name: 'Colombia', code: 'CO', code3: 'COL', capital: 'Bogotá', region: 'South America', subregion: 'South America', flagEmoji: '🇨🇴', phoneCode: '+57', currency: 'COP', currencySymbol: '$', languages: ['Spanish'], slug: 'colombia', ...base('Colombia') },
  { name: 'Ecuador', code: 'EC', code3: 'ECU', capital: 'Quito', region: 'South America', subregion: 'South America', flagEmoji: '🇪🇨', phoneCode: '+593', currency: 'USD', currencySymbol: '$', languages: ['Spanish'], slug: 'ecuador', ...base('Ecuador') },
  { name: 'Guyana', code: 'GY', code3: 'GUY', capital: 'Georgetown', region: 'South America', subregion: 'South America', flagEmoji: '🇬🇾', phoneCode: '+592', currency: 'GYD', currencySymbol: '$', languages: ['English'], slug: 'guyana', ...base('Guyana') },
  { name: 'Paraguay', code: 'PY', code3: 'PRY', capital: 'Asunción', region: 'South America', subregion: 'South America', flagEmoji: '🇵🇾', phoneCode: '+595', currency: 'PYG', currencySymbol: '₲', languages: ['Spanish', 'Guarani'], slug: 'paraguay', ...base('Paraguay') },
  { name: 'Peru', code: 'PE', code3: 'PER', capital: 'Lima', region: 'South America', subregion: 'South America', flagEmoji: '🇵🇪', phoneCode: '+51', currency: 'PEN', currencySymbol: 'S/', languages: ['Spanish', 'Quechua'], slug: 'peru', ...base('Peru') },
  { name: 'Suriname', code: 'SR', code3: 'SUR', capital: 'Paramaribo', region: 'South America', subregion: 'South America', flagEmoji: '🇸🇷', phoneCode: '+597', currency: 'SRD', currencySymbol: '$', languages: ['Dutch'], slug: 'suriname', ...base('Suriname') },
  { name: 'Uruguay', code: 'UY', code3: 'URY', capital: 'Montevideo', region: 'South America', subregion: 'South America', flagEmoji: '🇺🇾', phoneCode: '+598', currency: 'UYU', currencySymbol: '$', languages: ['Spanish'], slug: 'uruguay', ...base('Uruguay') },
  { name: 'Venezuela', code: 'VE', code3: 'VEN', capital: 'Caracas', region: 'South America', subregion: 'South America', flagEmoji: '🇻🇪', phoneCode: '+58', currency: 'VES', currencySymbol: 'Bs', languages: ['Spanish'], slug: 'venezuela', ...base('Venezuela') },

  // ─── Oceania ───────────────────────────────────────────────
  { name: 'Australia', code: 'AU', code3: 'AUS', capital: 'Canberra', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇦🇺', phoneCode: '+61', currency: 'AUD', currencySymbol: '$', languages: ['English'], slug: 'australia', ...base('Australia') },
  { name: 'Fiji', code: 'FJ', code3: 'FJI', capital: 'Suva', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇫🇯', phoneCode: '+679', currency: 'FJD', currencySymbol: '$', languages: ['English', 'Fijian'], slug: 'fiji', ...base('Fiji') },
  { name: 'Kiribati', code: 'KI', code3: 'KIR', capital: 'Tarawa', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇰🇮', phoneCode: '+686', currency: 'AUD', currencySymbol: '$', languages: ['English', 'Kiribati'], slug: 'kiribati', ...base('Kiribati') },
  { name: 'Marshall Islands', code: 'MH', code3: 'MHL', capital: 'Majuro', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇲🇭', phoneCode: '+692', currency: 'USD', currencySymbol: '$', languages: ['English', 'Marshallese'], slug: 'marshall-islands', ...base('Marshall Islands') },
  { name: 'Micronesia', code: 'FM', code3: 'FSM', capital: 'Palikir', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇫🇲', phoneCode: '+691', currency: 'USD', currencySymbol: '$', languages: ['English'], slug: 'micronesia', ...base('Micronesia') },
  { name: 'Nauru', code: 'NR', code3: 'NRU', capital: 'Yaren', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇳🇷', phoneCode: '+674', currency: 'AUD', currencySymbol: '$', languages: ['English', 'Nauruan'], slug: 'nauru', ...base('Nauru') },
  { name: 'New Zealand', code: 'NZ', code3: 'NZL', capital: 'Wellington', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇳🇿', phoneCode: '+64', currency: 'NZD', currencySymbol: '$', languages: ['English', 'Maori'], slug: 'new-zealand', ...base('New Zealand') },
  { name: 'Palau', code: 'PW', code3: 'PLW', capital: 'Ngerulmud', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇵🇼', phoneCode: '+680', currency: 'USD', currencySymbol: '$', languages: ['English', 'Palauan'], slug: 'palau', ...base('Palau') },
  { name: 'Papua New Guinea', code: 'PG', code3: 'PNG', capital: 'Port Moresby', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇵🇬', phoneCode: '+675', currency: 'PGK', currencySymbol: 'K', languages: ['English'], slug: 'papua-new-guinea', ...base('Papua New Guinea') },
  { name: 'Samoa', code: 'WS', code3: 'WSM', capital: 'Apia', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇼🇸', phoneCode: '+685', currency: 'WST', currencySymbol: 'T', languages: ['Samoan', 'English'], slug: 'samoa', ...base('Samoa') },
  { name: 'Solomon Islands', code: 'SB', code3: 'SLB', capital: 'Honiara', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇸🇧', phoneCode: '+677', currency: 'SBD', currencySymbol: '$', languages: ['English'], slug: 'solomon-islands', ...base('Solomon Islands') },
  { name: 'Tonga', code: 'TO', code3: 'TON', capital: "Nuku'alofa", region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇹🇴', phoneCode: '+676', currency: 'TOP', currencySymbol: 'T$', languages: ['Tongan', 'English'], slug: 'tonga', ...base('Tonga') },
  { name: 'Tuvalu', code: 'TV', code3: 'TUV', capital: 'Funafuti', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇹🇻', phoneCode: '+688', currency: 'AUD', currencySymbol: '$', languages: ['English', 'Tuvaluan'], slug: 'tuvalu', ...base('Tuvalu') },
  { name: 'Vanuatu', code: 'VU', code3: 'VUT', capital: 'Port Vila', region: 'Oceania', subregion: 'Oceania', flagEmoji: '🇻🇺', phoneCode: '+678', currency: 'VUV', currencySymbol: '₡', languages: ['English', 'French', 'Bislama'], slug: 'vanuatu', ...base('Vanuatu') },
];