import { countriesData } from "./countries.seed";
import { coreVisaCategoriesData, getCoreVisaTypeCode } from "./visa-types.seed";

/**
 * Visa Requirements Seed Data
 * Maps document requirements to visa type codes.
 * documentType values must match your documentTypeEnum.
 */

export type VisaRequirementSeed = {
  visaTypeCode: string;
  documentType: string;
  name: string;
  description: string;
  isRequired: boolean;
  isOptional: boolean;
  sortOrder: number;
  helpText: string;
  maxFileSizeMB: number;
  allowedFormats: string[];
};

const curatedVisaRequirementsData: VisaRequirementSeed[] = [
  // ─────────────── Common to all UAE visas ───────────────
  {
    visaTypeCode: "UAE_TOURIST_30_SINGLE",
    documentType: "PASSPORT_COPY",
    name: "Passport Bio-data Page",
    description: "Clear scanned copy of the passport biographical page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText:
      "Passport must be valid for at least 6 months beyond your travel date.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "UAE_TOURIST_30_SINGLE",
    documentType: "PASSPORT_PHOTO",
    name: "Recent Passport Photo",
    description: "White background, no glasses, taken within last 6 months.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "Photo must be 35mm x 45mm, white background, no borders.",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "UAE_TOURIST_30_SINGLE",
    documentType: "FLIGHT_ITINERARY",
    name: "Flight Itinerary / Booking Confirmation",
    description: "Round-trip or onward flight booking showing entry and exit.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText: "Must show your name, flight numbers, and travel dates.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "UAE_TOURIST_30_SINGLE",
    documentType: "HOTEL_BOOKING",
    name: "Hotel Booking / Accommodation Proof",
    description: "Confirmed hotel reservation for your stay in the UAE.",
    isRequired: true,
    isOptional: false,
    sortOrder: 4,
    helpText: "Must cover the entire duration of your stay.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "UAE_TOURIST_30_SINGLE",
    documentType: "BANK_STATEMENT",
    name: "Bank Statement (Last 3 Months)",
    description: "Evidence of sufficient funds to cover your stay.",
    isRequired: true,
    isOptional: false,
    sortOrder: 5,
    helpText: "Must show a minimum balance equivalent to USD 1,000.",
    maxFileSizeMB: 10,
    allowedFormats: ["pdf"],
  },
  {
    visaTypeCode: "UAE_TOURIST_30_SINGLE",
    documentType: "TRAVEL_INSURANCE",
    name: "Travel Insurance",
    description: "Travel and medical insurance covering your stay.",
    isRequired: false,
    isOptional: true,
    sortOrder: 6,
    helpText: "Recommended but not mandatory for tourist visa.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },

  // UAE 30 MULTI
  {
    visaTypeCode: "UAE_TOURIST_30_MULTI",
    documentType: "PASSPORT_COPY",
    name: "Passport Bio-data Page",
    description: "Clear scanned copy of the passport biographical page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Must be valid for at least 6 months from travel date.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "UAE_TOURIST_30_MULTI",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "White background passport-style photo.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "Must be recent (within 6 months).",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "UAE_TOURIST_30_MULTI",
    documentType: "BANK_STATEMENT",
    name: "Bank Statement (Last 3 Months)",
    description: "Proof of financial means for multiple visits.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText: "Minimum balance of USD 2,500 recommended.",
    maxFileSizeMB: 10,
    allowedFormats: ["pdf"],
  },
  {
    visaTypeCode: "UAE_TOURIST_30_MULTI",
    documentType: "EMPLOYMENT_LETTER",
    name: "Employment Letter or Business Registration",
    description: "Proof of employment or business ownership.",
    isRequired: true,
    isOptional: false,
    sortOrder: 4,
    helpText: "On company letterhead, signed by HR or management.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },

  // UAE 60 SINGLE
  {
    visaTypeCode: "UAE_TOURIST_60_SINGLE",
    documentType: "PASSPORT_COPY",
    name: "Passport Bio-data Page",
    description: "Clear scanned copy of the passport biographical page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Must be valid for at least 6 months from travel date.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "UAE_TOURIST_60_SINGLE",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "White background passport-style photo.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "Must be recent (within 6 months).",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "UAE_TOURIST_60_SINGLE",
    documentType: "BANK_STATEMENT",
    name: "Bank Statement (Last 3 Months)",
    description: "Proof of financial means for a 60-day stay.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText: "Minimum balance of USD 3,000 recommended.",
    maxFileSizeMB: 10,
    allowedFormats: ["pdf"],
  },
  {
    visaTypeCode: "UAE_TOURIST_60_SINGLE",
    documentType: "FLIGHT_ITINERARY",
    name: "Return Flight Booking",
    description: "Confirmed return or onward travel booking.",
    isRequired: true,
    isOptional: false,
    sortOrder: 4,
    helpText: "Must show departure within 60 days of entry.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "UAE_TOURIST_60_SINGLE",
    documentType: "HOTEL_BOOKING",
    name: "Hotel / Accommodation Proof",
    description: "Confirmed accommodation for your stay.",
    isRequired: true,
    isOptional: false,
    sortOrder: 5,
    helpText: "Must cover the full 60-day period or partial with reason.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },

  // ─────────────── Turkey ───────────────
  {
    visaTypeCode: "TR_TOURIST_30_SINGLE",
    documentType: "PASSPORT_COPY",
    name: "Passport Biographical Page",
    description: "Scanned copy of passport data page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText:
      "Passport must be valid at least 150 days beyond your intended stay.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "TR_TOURIST_30_SINGLE",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "Recent biometric photo.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "White background, facing forward, no headwear.",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "TR_TOURIST_30_SINGLE",
    documentType: "TRAVEL_INSURANCE",
    name: "Travel Health Insurance",
    description: "Insurance valid for the duration of stay in Turkey.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText: "Must cover medical expenses up to USD 30,000.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },

  {
    visaTypeCode: "TR_TOURIST_90_MULTI",
    documentType: "PASSPORT_COPY",
    name: "Passport Biographical Page",
    description: "Scanned copy of passport data page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Must be valid for 150 days beyond intended stay.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "TR_TOURIST_90_MULTI",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "Recent biometric photo.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "White background, facing forward.",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "TR_TOURIST_90_MULTI",
    documentType: "BANK_STATEMENT",
    name: "Bank Statement",
    description: "Proof of sufficient funds.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText: "Last 3 months, showing ability to fund multiple trips.",
    maxFileSizeMB: 10,
    allowedFormats: ["pdf"],
  },
  {
    visaTypeCode: "TR_TOURIST_90_MULTI",
    documentType: "TRAVEL_INSURANCE",
    name: "Travel Health Insurance",
    description: "Insurance covering all visits to Turkey.",
    isRequired: true,
    isOptional: false,
    sortOrder: 4,
    helpText: "Must cover medical expenses for all planned visits.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },

  // ─────────────── India ───────────────
  {
    visaTypeCode: "IN_ETOURIST_30",
    documentType: "PASSPORT_COPY",
    name: "Passport Front & Last Page",
    description: "Photo page and last page of passport.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Passport must have at least 2 blank pages.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "IN_ETOURIST_30",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "Recent colour photograph.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "2x2 inch, white background, no glasses, taken within 6 months.",
    maxFileSizeMB: 1,
    allowedFormats: ["jpg", "jpeg"],
  },
  {
    visaTypeCode: "IN_ETOURIST_30",
    documentType: "FLIGHT_ITINERARY",
    name: "Onward / Return Ticket",
    description: "Confirmed ticket showing departure from India.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText: "Must be within the 30-day visa window.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },

  {
    visaTypeCode: "IN_ETOURIST_1Y",
    documentType: "PASSPORT_COPY",
    name: "Passport Front & Last Page",
    description: "Photo page and last page of passport.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Passport must have at least 2 blank pages.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "IN_ETOURIST_1Y",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "Recent colour photograph.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "2x2 inch, white background, no glasses.",
    maxFileSizeMB: 1,
    allowedFormats: ["jpg", "jpeg"],
  },
  {
    visaTypeCode: "IN_ETOURIST_1Y",
    documentType: "BANK_STATEMENT",
    name: "Bank Statement",
    description: "3-month bank statement showing adequate funds.",
    isRequired: false,
    isOptional: true,
    sortOrder: 3,
    helpText: "Recommended to avoid refusals.",
    maxFileSizeMB: 10,
    allowedFormats: ["pdf"],
  },

  {
    visaTypeCode: "IN_EBUSINESS_1Y",
    documentType: "PASSPORT_COPY",
    name: "Passport Front & Last Page",
    description: "Photo page and last page of passport.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Must be valid for 6 months beyond stay.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "IN_EBUSINESS_1Y",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "Recent passport-style photo.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "2x2 inch white background.",
    maxFileSizeMB: 1,
    allowedFormats: ["jpg", "jpeg"],
  },
  {
    visaTypeCode: "IN_EBUSINESS_1Y",
    documentType: "BUSINESS_REGISTRATION",
    name: "Business Registration / Invitation Letter",
    description:
      "Business registration document or letter of invitation from Indian counterpart.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText: "Must state purpose of business visit.",
    maxFileSizeMB: 10,
    allowedFormats: ["pdf"],
  },
  {
    visaTypeCode: "IN_EBUSINESS_1Y",
    documentType: "EMPLOYMENT_LETTER",
    name: "Employment Letter",
    description: "Letter from employer confirming business travel.",
    isRequired: true,
    isOptional: false,
    sortOrder: 4,
    helpText: "On company letterhead with contact details.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },

  // ─────────────── Kenya ───────────────
  {
    visaTypeCode: "KE_TOURIST_90_SINGLE",
    documentType: "PASSPORT_COPY",
    name: "Passport Bio-data Page",
    description: "Scanned copy of passport information page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Must be valid for at least 6 months.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "KE_TOURIST_90_SINGLE",
    documentType: "PASSPORT_PHOTO",
    name: "Passport-size Photo",
    description: "Colour photo taken within last 6 months.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "White background, front-facing, no glasses.",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "KE_TOURIST_90_SINGLE",
    documentType: "YELLOW_FEVER_CERT",
    name: "Yellow Fever Vaccination Certificate",
    description: "International Certificate of Vaccination for yellow fever.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText:
      "Required if travelling from or through yellow fever endemic countries.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "KE_TOURIST_90_SINGLE",
    documentType: "FLIGHT_ITINERARY",
    name: "Return Flight Booking",
    description: "Confirmed return flight booking.",
    isRequired: true,
    isOptional: false,
    sortOrder: 4,
    helpText: "Must show departure before 90-day limit.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },
  {
    visaTypeCode: "KE_TOURIST_90_SINGLE",
    documentType: "HOTEL_BOOKING",
    name: "Accommodation Booking",
    description: "Hotel reservation or host letter.",
    isRequired: true,
    isOptional: false,
    sortOrder: 5,
    helpText: "At least first and last night must be confirmed.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },

  // ─────────────── Egypt ───────────────
  {
    visaTypeCode: "EG_TOURIST_30_SINGLE",
    documentType: "PASSPORT_COPY",
    name: "Passport Biographical Page",
    description: "Scanned copy of passport data page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Passport valid for at least 6 months beyond travel dates.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "EG_TOURIST_30_SINGLE",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "White background passport photo.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "Must be taken within the last 6 months.",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "EG_TOURIST_30_SINGLE",
    documentType: "FLIGHT_ITINERARY",
    name: "Flight Booking",
    description: "Onward or return travel booking.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText: "Must show departure within 30 days of entry.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },

  {
    visaTypeCode: "EG_TOURIST_30_MULTI",
    documentType: "PASSPORT_COPY",
    name: "Passport Biographical Page",
    description: "Clear scan of passport data page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "At least 6 months validity required.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "EG_TOURIST_30_MULTI",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "Recent passport-style photo.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "White background, within last 6 months.",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "EG_TOURIST_30_MULTI",
    documentType: "BANK_STATEMENT",
    name: "Bank Statement",
    description: "Proof of funds for multiple trips.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText: "Last 3 months statements required.",
    maxFileSizeMB: 10,
    allowedFormats: ["pdf"],
  },

  // ─────────────── Sri Lanka ───────────────
  {
    visaTypeCode: "LK_ETA_30",
    documentType: "PASSPORT_COPY",
    name: "Passport Bio Page",
    description: "Scanned passport biographical page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Minimum 6 months validity from date of entry.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "LK_ETA_30",
    documentType: "FLIGHT_ITINERARY",
    name: "Return / Onward Travel",
    description: "Confirmed flight out of Sri Lanka.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "Must show departure within the 30-day window.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },
  {
    visaTypeCode: "LK_ETA_30",
    documentType: "HOTEL_BOOKING",
    name: "Accommodation Details",
    description: "First hotel booking or host details.",
    isRequired: false,
    isOptional: true,
    sortOrder: 3,
    helpText: "Recommended to provide to avoid delays at immigration.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },

  // ─────────────── Cambodia ───────────────
  {
    visaTypeCode: "KH_TOURIST_30",
    documentType: "PASSPORT_COPY",
    name: "Passport Bio-data Page",
    description: "Scanned copy of personal details page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Must be valid for at least 6 months.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "KH_TOURIST_30",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "White background colour photo.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "Must be taken within the last 6 months.",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },

  // ─────────────── Vietnam ───────────────
  {
    visaTypeCode: "VN_TOURIST_90_SINGLE",
    documentType: "PASSPORT_COPY",
    name: "Passport Biographical Page",
    description: "Scan of passport personal details page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Must be valid at least 6 months from entry date.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "VN_TOURIST_90_SINGLE",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "Colour photo with white background.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "Front-facing, no glasses, white background.",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "VN_TOURIST_90_SINGLE",
    documentType: "FLIGHT_ITINERARY",
    name: "Return Flight",
    description: "Confirmed return or onward travel booking.",
    isRequired: false,
    isOptional: true,
    sortOrder: 3,
    helpText: "Recommended; immigration officers may ask.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },

  {
    visaTypeCode: "VN_TOURIST_90_MULTI",
    documentType: "PASSPORT_COPY",
    name: "Passport Biographical Page",
    description: "Scan of passport personal details page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Must be valid at least 6 months from entry date.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "VN_TOURIST_90_MULTI",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "Colour photo with white background.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "Front-facing, no glasses.",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },

  // ─────────────── Ethiopia ───────────────
  {
    visaTypeCode: "ET_TOURIST_30",
    documentType: "PASSPORT_COPY",
    name: "Passport Bio-data Page",
    description: "Clear scan of passport information page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Must be valid for at least 6 months from entry.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "ET_TOURIST_30",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "Recent passport-style photo.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "White background, front-facing.",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "ET_TOURIST_30",
    documentType: "FLIGHT_ITINERARY",
    name: "Flight Booking",
    description: "Confirmed return or onward travel.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText: "Must depart within the 30-day visa period.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },
  {
    visaTypeCode: "ET_TOURIST_30",
    documentType: "YELLOW_FEVER_CERT",
    name: "Yellow Fever Certificate",
    description: "Required if arriving from endemic countries.",
    isRequired: false,
    isOptional: true,
    sortOrder: 4,
    helpText: "Check if required based on your origin country.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },

  // ─────────────── Azerbaijan ───────────────
  {
    visaTypeCode: "AZ_ASAN_30",
    documentType: "PASSPORT_COPY",
    name: "Passport Scan",
    description: "Scanned passport data page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "6 months validity required beyond stay duration.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "AZ_ASAN_30",
    documentType: "PASSPORT_PHOTO",
    name: "Digital Passport Photo",
    description: "Recent passport-style photo.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "Plain white background, taken within 6 months.",
    maxFileSizeMB: 2,
    allowedFormats: ["jpg", "jpeg", "png"],
  },

  // ─────────────── Bahrain ───────────────
  {
    visaTypeCode: "BH_TOURIST_14",
    documentType: "PASSPORT_COPY",
    name: "Passport Biographical Page",
    description: "Clear scan of passport personal details.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Valid for at least 6 months from entry date.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "BH_TOURIST_14",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "White background passport photo.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "Recent, facing forward.",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "BH_TOURIST_14",
    documentType: "HOTEL_BOOKING",
    name: "Hotel Confirmation",
    description: "Booking confirmation for your stay in Bahrain.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText: "Must cover all nights of your 14-day stay.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },

  // ─────────────── Qatar ───────────────
  {
    visaTypeCode: "QA_TOURIST_30",
    documentType: "PASSPORT_COPY",
    name: "Passport Bio Page",
    description: "Passport personal details page scan.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Passport must be valid for at least 6 months.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "QA_TOURIST_30",
    documentType: "PASSPORT_PHOTO",
    name: "Passport Photo",
    description: "Recent passport-style photo.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "White background, front-facing.",
    maxFileSizeMB: 3,
    allowedFormats: ["jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "QA_TOURIST_30",
    documentType: "HOTEL_BOOKING",
    name: "Hotel Reservation",
    description: "Confirmed accommodation in Qatar.",
    isRequired: true,
    isOptional: false,
    sortOrder: 3,
    helpText: "Required as part of the Qatar visa application.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },
  {
    visaTypeCode: "QA_TOURIST_30",
    documentType: "FLIGHT_ITINERARY",
    name: "Return Flight",
    description: "Confirmed return or onward flight booking.",
    isRequired: true,
    isOptional: false,
    sortOrder: 4,
    helpText: "Departure must be within 30 days.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },

  // ─────────────── UAE Transit ───────────────
  {
    visaTypeCode: "UAE_TRANSIT_96H",
    documentType: "PASSPORT_COPY",
    name: "Passport Bio Page",
    description: "Scanned personal details page.",
    isRequired: true,
    isOptional: false,
    sortOrder: 1,
    helpText: "Must be valid for 6 months minimum.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
  {
    visaTypeCode: "UAE_TRANSIT_96H",
    documentType: "FLIGHT_ITINERARY",
    name: "Onward Flight Ticket",
    description: "Confirmed onward flight showing you are transiting the UAE.",
    isRequired: true,
    isOptional: false,
    sortOrder: 2,
    helpText: "Must show your final destination beyond the UAE.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf"],
  },
  {
    visaTypeCode: "UAE_TRANSIT_96H",
    documentType: "VISA_FOR_DESTINATION",
    name: "Destination Country Visa",
    description: "Valid visa or entry permit for your final destination.",
    isRequired: false,
    isOptional: true,
    sortOrder: 3,
    helpText: "Required if your destination country requires a visa.",
    maxFileSizeMB: 5,
    allowedFormats: ["pdf", "jpg", "jpeg", "png"],
  },
];

type RequirementTemplate = Omit<
  VisaRequirementSeed,
  "visaTypeCode" | "sortOrder"
>;

const generatedRequirementTemplates: Record<
  (typeof coreVisaCategoriesData)[number]["key"],
  RequirementTemplate[]
> = {
  TOURISM: [
    {
      documentType: "PASSPORT_COPY",
      name: "Passport Bio-data Page",
      description: "Clear scanned copy of the passport biographical page.",
      isRequired: true,
      isOptional: false,
      helpText:
        "Passport should be valid for at least 6 months beyond the intended stay.",
      maxFileSizeMB: 5,
      allowedFormats: ["pdf", "jpg", "jpeg", "png"],
    },
    {
      documentType: "PASSPORT_PHOTO",
      name: "Recent Passport Photo",
      description: "Recent passport-style photo on a plain background.",
      isRequired: true,
      isOptional: false,
      helpText: "Use a clear color photo taken within the last 6 months.",
      maxFileSizeMB: 3,
      allowedFormats: ["jpg", "jpeg", "png"],
    },
    {
      documentType: "FLIGHT_ITINERARY",
      name: "Flight Itinerary",
      description:
        "Round-trip or onward travel itinerary showing planned arrival and departure.",
      isRequired: true,
      isOptional: false,
      helpText:
        "A reservation or itinerary is acceptable unless official instructions require a paid ticket.",
      maxFileSizeMB: 5,
      allowedFormats: ["pdf", "jpg", "jpeg", "png"],
    },
    {
      documentType: "HOTEL_BOOKING",
      name: "Accommodation Proof",
      description:
        "Hotel booking, invitation from host, or other proof of accommodation.",
      isRequired: true,
      isOptional: false,
      helpText: "The accommodation proof should cover the intended stay.",
      maxFileSizeMB: 5,
      allowedFormats: ["pdf", "jpg", "jpeg", "png"],
    },
    {
      documentType: "BANK_STATEMENT",
      name: "Bank Statement",
      description:
        "Recent bank statement demonstrating sufficient funds for travel.",
      isRequired: true,
      isOptional: false,
      helpText:
        "Upload statements covering the most recent 3 months where available.",
      maxFileSizeMB: 10,
      allowedFormats: ["pdf"],
    },
  ],
  STUDENT: [
    {
      documentType: "PASSPORT_COPY",
      name: "Passport Bio-data Page",
      description: "Clear scanned copy of the passport biographical page.",
      isRequired: true,
      isOptional: false,
      helpText: "Passport should be valid beyond the planned study period.",
      maxFileSizeMB: 5,
      allowedFormats: ["pdf", "jpg", "jpeg", "png"],
    },
    {
      documentType: "PASSPORT_PHOTO",
      name: "Recent Passport Photo",
      description: "Recent passport-style photo on a plain background.",
      isRequired: true,
      isOptional: false,
      helpText: "Use a clear color photo taken within the last 6 months.",
      maxFileSizeMB: 3,
      allowedFormats: ["jpg", "jpeg", "png"],
    },
    {
      documentType: "INVITATION_LETTER",
      name: "Admission or Enrollment Letter",
      description:
        "Official admission, enrollment, or acceptance letter from the education provider.",
      isRequired: true,
      isOptional: false,
      helpText:
        "The letter should show the applicant name, program, institution, and study dates.",
      maxFileSizeMB: 5,
      allowedFormats: ["pdf"],
    },
    {
      documentType: "FINANCIAL_PROOF",
      name: "Proof of Financial Support",
      description:
        "Evidence of funds or sponsorship for tuition and living costs.",
      isRequired: true,
      isOptional: false,
      helpText:
        "Upload scholarship letters, sponsor letters, or financial statements.",
      maxFileSizeMB: 10,
      allowedFormats: ["pdf", "jpg", "jpeg", "png"],
    },
    {
      documentType: "TRAVEL_INSURANCE",
      name: "Health or Travel Insurance",
      description:
        "Insurance coverage for the intended study period where required.",
      isRequired: false,
      isOptional: true,
      helpText:
        "Recommended for all student travelers and mandatory for some destinations.",
      maxFileSizeMB: 5,
      allowedFormats: ["pdf"],
    },
  ],
  WORK: [
    {
      documentType: "PASSPORT_COPY",
      name: "Passport Bio-data Page",
      description: "Clear scanned copy of the passport biographical page.",
      isRequired: true,
      isOptional: false,
      helpText:
        "Passport should be valid beyond the planned work authorization period.",
      maxFileSizeMB: 5,
      allowedFormats: ["pdf", "jpg", "jpeg", "png"],
    },
    {
      documentType: "PASSPORT_PHOTO",
      name: "Recent Passport Photo",
      description: "Recent passport-style photo on a plain background.",
      isRequired: true,
      isOptional: false,
      helpText: "Use a clear color photo taken within the last 6 months.",
      maxFileSizeMB: 3,
      allowedFormats: ["jpg", "jpeg", "png"],
    },
    {
      documentType: "EMPLOYMENT_LETTER",
      name: "Employment Offer or Contract",
      description:
        "Signed employment offer, contract, or assignment letter from the sponsoring employer.",
      isRequired: true,
      isOptional: false,
      helpText:
        "The document should include role, employer, salary, and expected start date.",
      maxFileSizeMB: 5,
      allowedFormats: ["pdf"],
    },
    {
      documentType: "BUSINESS_REGISTRATION",
      name: "Employer Registration Document",
      description:
        "Business registration or sponsor license document for the employer where applicable.",
      isRequired: false,
      isOptional: true,
      helpText:
        "Upload this if requested by the destination country or sponsor.",
      maxFileSizeMB: 5,
      allowedFormats: ["pdf", "jpg", "jpeg", "png"],
    },
    {
      documentType: "BANK_STATEMENT",
      name: "Bank Statement",
      description: "Recent bank statement or financial support evidence.",
      isRequired: true,
      isOptional: false,
      helpText:
        "Upload statements covering the most recent 3 months where available.",
      maxFileSizeMB: 10,
      allowedFormats: ["pdf"],
    },
  ],
};

const curatedRequirementKeys = new Set(
  curatedVisaRequirementsData.map(
    (requirement) =>
      `${requirement.visaTypeCode}:${requirement.documentType}:${requirement.name}`,
  ),
);

const generatedVisaRequirementsData: VisaRequirementSeed[] =
  countriesData.flatMap((country) =>
    coreVisaCategoriesData.flatMap((category) =>
      generatedRequirementTemplates[category.key]
        .map((template, index) => ({
          visaTypeCode: getCoreVisaTypeCode(country, category),
          ...template,
          sortOrder: index + 1,
        }))
        .filter(
          (requirement) =>
            !curatedRequirementKeys.has(
              `${requirement.visaTypeCode}:${requirement.documentType}:${requirement.name}`,
            ),
        ),
    ),
  );

export const visaRequirementsData: VisaRequirementSeed[] = [
  ...curatedVisaRequirementsData,
  ...generatedVisaRequirementsData,
];
