/**
 * Visa Types Seed Data
 * Covers popular e-visa destinations with realistic pricing, processing times, and details.
 * Prices are in USD cents. nationalityCountryId: null = open to all nationalities.
 */

export type VisaTypeSeed = {
  name: string;
  code: string;
  slug: string;
  destinationCountryCode: string;
  nationalityCountryCode: string | null; // null = all nationalities
  entryType: 'SINGLE' | 'MULTIPLE' | 'TRANSIT' | 'DOUBLE';
  stayDuration: number;
  validityPeriod: number;
  description: string;
  notes: string;
  isVisaRequired: boolean;
  isVisaOnArrival: boolean;
  isEVisa: boolean;
  processingDaysMin: number;
  processingDaysMax: number;
  processingDaysExpedited: number | null;
  processingDaysRush: number | null;
  priceStandard: number; // cents
  priceExpedited: number | null; // cents
  priceRush: number | null; // cents
  govFee: number; // cents
  serviceFee: number; // cents
  isPublished: boolean;
  sortOrder: number;
};

export const visaTypesData: VisaTypeSeed[] = [
  // ─────────────── UAE (United Arab Emirates) ───────────────
  {
    name: 'UAE Tourist Visa - 30 Days Single Entry',
    code: 'UAE_TOURIST_30_SINGLE',
    slug: 'uae-tourist-visa-30-days-single',
    destinationCountryCode: 'AE',
    nationalityCountryCode: null,
    entryType: 'SINGLE',
    stayDuration: 30,
    validityPeriod: 60,
    description: 'Single-entry tourist visa for the United Arab Emirates valid for 30 days stay.',
    notes: 'Must be used within 60 days of issue. Not extendable.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 3,
    processingDaysMax: 7,
    processingDaysExpedited: 2,
    processingDaysRush: 1,
    priceStandard: 9900,
    priceExpedited: 13900,
    priceRush: 17900,
    govFee: 6300,
    serviceFee: 3600,
    isPublished: true,
    sortOrder: 1,
  },
  {
    name: 'UAE Tourist Visa - 30 Days Multiple Entry',
    code: 'UAE_TOURIST_30_MULTI',
    slug: 'uae-tourist-visa-30-days-multiple',
    destinationCountryCode: 'AE',
    nationalityCountryCode: null,
    entryType: 'MULTIPLE',
    stayDuration: 30,
    validityPeriod: 90,
    description: 'Multiple-entry tourist visa for the UAE. Each stay limited to 30 days.',
    notes: 'Ideal for frequent visitors. Each entry allows up to 30 days.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 3,
    processingDaysMax: 7,
    processingDaysExpedited: 2,
    processingDaysRush: 1,
    priceStandard: 14900,
    priceExpedited: 18900,
    priceRush: 22900,
    govFee: 10300,
    serviceFee: 4600,
    isPublished: true,
    sortOrder: 2,
  },
  {
    name: 'UAE Tourist Visa - 60 Days Single Entry',
    code: 'UAE_TOURIST_60_SINGLE',
    slug: 'uae-tourist-visa-60-days-single',
    destinationCountryCode: 'AE',
    nationalityCountryCode: null,
    entryType: 'SINGLE',
    stayDuration: 60,
    validityPeriod: 90,
    description: 'Long-stay tourist visa for the UAE, allowing 60 days in-country.',
    notes: 'Perfect for extended visits or business trips.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 3,
    processingDaysMax: 7,
    processingDaysExpedited: 2,
    processingDaysRush: 1,
    priceStandard: 17900,
    priceExpedited: 21900,
    priceRush: 25900,
    govFee: 13000,
    serviceFee: 4900,
    isPublished: true,
    sortOrder: 3,
  },
  {
    name: 'UAE Transit Visa - 96 Hours',
    code: 'UAE_TRANSIT_96H',
    slug: 'uae-transit-visa-96-hours',
    destinationCountryCode: 'AE',
    nationalityCountryCode: null,
    entryType: 'TRANSIT',
    stayDuration: 4,
    validityPeriod: 14,
    description: 'Short transit visa allowing a 96-hour layover in the UAE.',
    notes: 'Ideal for stopover travelers wanting to explore Dubai.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 2,
    processingDaysMax: 5,
    processingDaysExpedited: 1,
    processingDaysRush: null,
    priceStandard: 4900,
    priceExpedited: 7900,
    priceRush: null,
    govFee: 2700,
    serviceFee: 2200,
    isPublished: true,
    sortOrder: 4,
  },

  // ─────────────── Turkey ───────────────
  {
    name: 'Turkey e-Visa - Single Entry',
    code: 'TR_TOURIST_30_SINGLE',
    slug: 'turkey-evisa-single-entry',
    destinationCountryCode: 'TR',
    nationalityCountryCode: null,
    entryType: 'SINGLE',
    stayDuration: 30,
    validityPeriod: 180,
    description: 'Official Turkish e-Visa for tourism or business, single entry.',
    notes: 'e-Visa must be printed or shown on mobile at entry. Valid for 180 days from issue.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 1,
    processingDaysMax: 3,
    processingDaysExpedited: 1,
    processingDaysRush: null,
    priceStandard: 6900,
    priceExpedited: 9900,
    priceRush: null,
    govFee: 5000,
    serviceFee: 1900,
    isPublished: true,
    sortOrder: 1,
  },
  {
    name: 'Turkey e-Visa - Multiple Entry',
    code: 'TR_TOURIST_90_MULTI',
    slug: 'turkey-evisa-multiple-entry',
    destinationCountryCode: 'TR',
    nationalityCountryCode: null,
    entryType: 'MULTIPLE',
    stayDuration: 90,
    validityPeriod: 180,
    description: 'Multiple-entry Turkish e-Visa, up to 90 days total stay within 180 days.',
    notes: 'Not available for all nationalities. Check eligibility.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 1,
    processingDaysMax: 3,
    processingDaysExpedited: 1,
    processingDaysRush: null,
    priceStandard: 10900,
    priceExpedited: 13900,
    priceRush: null,
    govFee: 8500,
    serviceFee: 2400,
    isPublished: true,
    sortOrder: 2,
  },

  // ─────────────── India ───────────────
  {
    name: 'India e-Tourist Visa - 30 Days',
    code: 'IN_ETOURIST_30',
    slug: 'india-e-tourist-visa-30-days',
    destinationCountryCode: 'IN',
    nationalityCountryCode: null,
    entryType: 'DOUBLE',
    stayDuration: 30,
    validityPeriod: 30,
    description: 'India e-Tourist Visa for short tourism visits, double entry within 30 days.',
    notes: 'Allows two entries within the 30-day validity period.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 2,
    processingDaysMax: 4,
    processingDaysExpedited: null,
    processingDaysRush: null,
    priceStandard: 7900,
    priceExpedited: null,
    priceRush: null,
    govFee: 2500,
    serviceFee: 5400,
    isPublished: true,
    sortOrder: 1,
  },
  {
    name: 'India e-Tourist Visa - 1 Year',
    code: 'IN_ETOURIST_1Y',
    slug: 'india-e-tourist-visa-1-year',
    destinationCountryCode: 'IN',
    nationalityCountryCode: null,
    entryType: 'MULTIPLE',
    stayDuration: 90,
    validityPeriod: 365,
    description: 'India e-Tourist Visa valid for 1 year with multiple entries, up to 90 days per visit.',
    notes: 'Each stay must not exceed 90 consecutive days.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 2,
    processingDaysMax: 4,
    processingDaysExpedited: null,
    processingDaysRush: null,
    priceStandard: 11900,
    priceExpedited: null,
    priceRush: null,
    govFee: 4000,
    serviceFee: 7900,
    isPublished: true,
    sortOrder: 2,
  },
  {
    name: 'India e-Business Visa',
    code: 'IN_EBUSINESS_1Y',
    slug: 'india-e-business-visa',
    destinationCountryCode: 'IN',
    nationalityCountryCode: null,
    entryType: 'MULTIPLE',
    stayDuration: 180,
    validityPeriod: 365,
    description: 'India e-Business Visa for business meetings, trade fairs, and commercial activities.',
    notes: 'Not valid for employment or journalism.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 2,
    processingDaysMax: 4,
    processingDaysExpedited: null,
    processingDaysRush: null,
    priceStandard: 13900,
    priceExpedited: null,
    priceRush: null,
    govFee: 4000,
    serviceFee: 9900,
    isPublished: true,
    sortOrder: 3,
  },

  // ─────────────── Kenya ───────────────
  {
    name: 'Kenya e-Visa - Single Entry',
    code: 'KE_TOURIST_90_SINGLE',
    slug: 'kenya-evisa-single-entry',
    destinationCountryCode: 'KE',
    nationalityCountryCode: null,
    entryType: 'SINGLE',
    stayDuration: 90,
    validityPeriod: 90,
    description: 'Kenya Electronic Travel Authorization (ETA) for tourism or business.',
    notes: 'Kenya now issues an ETA instead of a traditional e-Visa.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 3,
    processingDaysMax: 7,
    processingDaysExpedited: null,
    processingDaysRush: null,
    priceStandard: 7900,
    priceExpedited: null,
    priceRush: null,
    govFee: 5000,
    serviceFee: 2900,
    isPublished: true,
    sortOrder: 1,
  },

  // ─────────────── Egypt ───────────────
  {
    name: 'Egypt e-Visa - Single Entry',
    code: 'EG_TOURIST_30_SINGLE',
    slug: 'egypt-evisa-single-entry',
    destinationCountryCode: 'EG',
    nationalityCountryCode: null,
    entryType: 'SINGLE',
    stayDuration: 30,
    validityPeriod: 90,
    description: 'Egyptian single-entry e-Visa for tourism.',
    notes: 'Visa is valid for 90 days from issue; use within that window.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 3,
    processingDaysMax: 7,
    processingDaysExpedited: 2,
    processingDaysRush: null,
    priceStandard: 7500,
    priceExpedited: 10500,
    priceRush: null,
    govFee: 2500,
    serviceFee: 5000,
    isPublished: true,
    sortOrder: 1,
  },
  {
    name: 'Egypt e-Visa - Multiple Entry',
    code: 'EG_TOURIST_30_MULTI',
    slug: 'egypt-evisa-multiple-entry',
    destinationCountryCode: 'EG',
    nationalityCountryCode: null,
    entryType: 'MULTIPLE',
    stayDuration: 30,
    validityPeriod: 180,
    description: 'Egyptian multiple-entry e-Visa for repeated tourist visits.',
    notes: 'Each stay limited to 30 days.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 3,
    processingDaysMax: 7,
    processingDaysExpedited: 2,
    processingDaysRush: null,
    priceStandard: 10500,
    priceExpedited: 13500,
    priceRush: null,
    govFee: 5000,
    serviceFee: 5500,
    isPublished: true,
    sortOrder: 2,
  },

  // ─────────────── Sri Lanka ───────────────
  {
    name: 'Sri Lanka ETA - Short Stay',
    code: 'LK_ETA_30',
    slug: 'sri-lanka-eta-short-stay',
    destinationCountryCode: 'LK',
    nationalityCountryCode: null,
    entryType: 'MULTIPLE',
    stayDuration: 30,
    validityPeriod: 180,
    description: 'Sri Lanka Electronic Travel Authorization for tourism, short business, or transit.',
    notes: 'Extendable once in-country for up to another 30 days.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 1,
    processingDaysMax: 3,
    processingDaysExpedited: null,
    processingDaysRush: null,
    priceStandard: 4900,
    priceExpedited: null,
    priceRush: null,
    govFee: 2000,
    serviceFee: 2900,
    isPublished: true,
    sortOrder: 1,
  },

  // ─────────────── Cambodia ───────────────
  {
    name: 'Cambodia e-Visa - Tourist',
    code: 'KH_TOURIST_30',
    slug: 'cambodia-evisa-tourist',
    destinationCountryCode: 'KH',
    nationalityCountryCode: null,
    entryType: 'SINGLE',
    stayDuration: 30,
    validityPeriod: 90,
    description: 'Official Cambodian e-Visa for tourism purposes.',
    notes: 'Extendable inside Cambodia. Only valid at designated border crossings.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 3,
    processingDaysMax: 5,
    processingDaysExpedited: null,
    processingDaysRush: null,
    priceStandard: 5900,
    priceExpedited: null,
    priceRush: null,
    govFee: 3600,
    serviceFee: 2300,
    isPublished: true,
    sortOrder: 1,
  },

  // ─────────────── Ethiopia ───────────────
  {
    name: 'Ethiopia e-Visa - Tourist',
    code: 'ET_TOURIST_30',
    slug: 'ethiopia-evisa-tourist',
    destinationCountryCode: 'ET',
    nationalityCountryCode: null,
    entryType: 'SINGLE',
    stayDuration: 30,
    validityPeriod: 90,
    description: 'Ethiopian single-entry tourist e-Visa.',
    notes: 'Valid for Addis Ababa Bole International Airport entry only.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 3,
    processingDaysMax: 5,
    processingDaysExpedited: null,
    processingDaysRush: null,
    priceStandard: 5900,
    priceExpedited: null,
    priceRush: null,
    govFee: 5200,
    serviceFee: 700,
    isPublished: true,
    sortOrder: 1,
  },

  // ─────────────── Azerbaijan ───────────────
  {
    name: 'Azerbaijan ASAN e-Visa',
    code: 'AZ_ASAN_30',
    slug: 'azerbaijan-asan-evisa',
    destinationCountryCode: 'AZ',
    nationalityCountryCode: null,
    entryType: 'SINGLE',
    stayDuration: 30,
    validityPeriod: 90,
    description: 'Azerbaijan ASAN single-entry e-Visa for tourism and business.',
    notes: 'ASAN Visa is one of the fastest e-Visa systems in the world.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 3,
    processingDaysMax: 3,
    processingDaysExpedited: null,
    processingDaysRush: null,
    priceStandard: 4400,
    priceExpedited: null,
    priceRush: null,
    govFee: 2000,
    serviceFee: 2400,
    isPublished: true,
    sortOrder: 1,
  },

  // ─────────────── Bahrain ───────────────
  {
    name: 'Bahrain e-Visa - 14 Days',
    code: 'BH_TOURIST_14',
    slug: 'bahrain-evisa-14-days',
    destinationCountryCode: 'BH',
    nationalityCountryCode: null,
    entryType: 'SINGLE',
    stayDuration: 14,
    validityPeriod: 30,
    description: 'Bahrain single-entry tourist e-Visa for a 14-day stay.',
    notes: 'Extendable once in-country.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 1,
    processingDaysMax: 3,
    processingDaysExpedited: null,
    processingDaysRush: null,
    priceStandard: 5900,
    priceExpedited: null,
    priceRush: null,
    govFee: 2700,
    serviceFee: 3200,
    isPublished: true,
    sortOrder: 1,
  },

  // ─────────────── Qatar ───────────────
  {
    name: 'Qatar Hayya Visa - 30 Days',
    code: 'QA_TOURIST_30',
    slug: 'qatar-tourist-visa-30-days',
    destinationCountryCode: 'QA',
    nationalityCountryCode: null,
    entryType: 'SINGLE',
    stayDuration: 30,
    validityPeriod: 60,
    description: 'Qatar single-entry tourist visa for 30-day stays.',
    notes: 'Many nationalities receive free visas on arrival. Check eligibility.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 2,
    processingDaysMax: 5,
    processingDaysExpedited: 1,
    processingDaysRush: null,
    priceStandard: 5200,
    priceExpedited: 7900,
    priceRush: null,
    govFee: 1000,
    serviceFee: 4200,
    isPublished: true,
    sortOrder: 1,
  },

  // ─────────────── Vietnam ───────────────
  {
    name: 'Vietnam e-Visa - 90 Days Single',
    code: 'VN_TOURIST_90_SINGLE',
    slug: 'vietnam-evisa-90-days-single',
    destinationCountryCode: 'VN',
    nationalityCountryCode: null,
    entryType: 'SINGLE',
    stayDuration: 90,
    validityPeriod: 90,
    description: 'Vietnam single-entry e-Visa valid for 90 days.',
    notes: 'Valid at all international border checkpoints.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 3,
    processingDaysMax: 5,
    processingDaysExpedited: null,
    processingDaysRush: null,
    priceStandard: 5500,
    priceExpedited: null,
    priceRush: null,
    govFee: 2500,
    serviceFee: 3000,
    isPublished: true,
    sortOrder: 1,
  },
  {
    name: 'Vietnam e-Visa - 90 Days Multiple',
    code: 'VN_TOURIST_90_MULTI',
    slug: 'vietnam-evisa-90-days-multiple',
    destinationCountryCode: 'VN',
    nationalityCountryCode: null,
    entryType: 'MULTIPLE',
    stayDuration: 90,
    validityPeriod: 90,
    description: 'Vietnam multiple-entry e-Visa valid for 90 days.',
    notes: 'Best option for travelers making multiple trips.',
    isVisaRequired: true,
    isVisaOnArrival: false,
    isEVisa: true,
    processingDaysMin: 3,
    processingDaysMax: 5,
    processingDaysExpedited: null,
    processingDaysRush: null,
    priceStandard: 7500,
    priceExpedited: null,
    priceRush: null,
    govFee: 2500,
    serviceFee: 5000,
    isPublished: true,
    sortOrder: 2,
  },
];
